# Per-item metadata for the 61-doc numeric rewrite (2026-05-12).
# Each entry must be fed by hand from PDF + InfoSys.
#
# Shape:
#   "Name": {
#     "subdir":  "uint64" | "int64_signed" | "fix16" | "float" | "lcomplex",
#     "section": "4.x.y",
#     "ret":     "<return type>",
#     "inputs":  [(name, type, default-or-"-", chinese-desc), ...],
#     "in_out":  [(name, type, "-", chinese-desc), ...] | [],
#     "purpose": "中文 §1 第一句（不抄英文）",
#     "behavior":"中文 §3 行为段（≥80 CJK chars，含语义/取值范围/边界/陷阱）",
#     "ret_doc": "中文 §4 返回值与边界说明",
#     "pitfalls":["pit 1", "pit 2", ...],
#     "scenario":"§7 场景一段（中文）",
#     "value":   "§7 价值与替代方案",
#     "demo_vars": "局部变量声明（不含 fb 实例）",
#     "demo_call": "调用代码段",
#     "xml_localvars": "<variable>…</variable> 序列（不含 fb 实例）",
#     "xml_body":     "ST body（已转义）",
#   }
#
# Conventions:
#   - 所有 input/output 类型必须完全照搬 PDF 原文（含 STRING(N)/BYTE(0..15) 等）。
#   - "default" 列若 PDF 没 := 则填 "-"。
#   - demo 命名贴近工业语义，注释比例 ≥ 1/3。

# 共用片段，避免重复
ULI = "T_ULARGE_INTEGER"
LI  = "T_LARGE_INTEGER"

META = {}


def _add(name, **kw):
    META[name] = kw


# ===== 64 bit integer functions (unsigned) — 31 项 =====

_add("LREAL_TO_UINT64",
    subdir="uint64", section="4.9.1", ret=ULI,
    inputs=[("in","LREAL","-","待转换的浮点数；超出 0..2⁶⁴−1 的部分按 PDF 未定义")],
    in_out=[],
    purpose="把 LREAL 浮点数转换为 TwinCAT 2 的旧式无符号 64 位整数 `T_ULARGE_INTEGER`（高低各 32 位结构体）。当 PLC 里用 TwinCAT 2 移植代码、或与 ADS 报文里以 T_ULARGE_INTEGER 形式定义的字段交互时需要从浮点回到这种结构体表示。",
    behavior="本函数把 64 位浮点近似四舍五入或截断（PDF 未明确舍入模式 ⚠️）为一个 0..2⁶⁴−1 的整数，并按 dwHighPart/dwLowPart 写入 T_ULARGE_INTEGER 结构体。需要注意三个边界：第一，输入为负数时 PDF 未定义结果，工程实践应在调用前判断 `IF in < 0`；第二，输入大于 1.8E19（约 2⁶⁴）时 PDF 未定义溢出行为；第三，LREAL 在大于 2⁵³ 后只能表达整数的近似值，超过 9.007E15 的值会丢精度。返回结构体本身字段是 DWORD，可用 `ULARGE_TO_ULINT` 转换为原生 `ULINT` 后再做算术。",
    ret_doc="`T_ULARGE_INTEGER` —— 结构体表示的 64 位无符号整数。",
    pitfalls=[
        "负数 / 超出 2⁶⁴ 的输入 PDF 未定义 — 调用前自检",
        "LREAL 精度上限 2⁵³ ≈ 9E15，再大就只能近似",
        "结果是 legacy 结构体，下一步算术建议先用 `ULARGE_TO_ULINT` 转为 ULINT",
        "舍入模式 PDF 未列 ⚠️，与浮点四舍五入或截断行为相关的工程不要依赖此函数",
    ],
    scenario="把 PID 控制器算出的速度上限（LREAL）写入 ADS Raw 报文中按 T_ULARGE_INTEGER 定义的累计计数字段。",
    value="不用本函数得手写 LREAL 拆 DWORD 高低位再赋值给结构体两次，本函数一次返回；与 `Tc2_Utilities` 其它 64 位函数风格统一。",
    demo_vars="lrSetpoint   : LREAL := 1.5E12;   // 业务侧浮点（如累计产量上限）\n    uliConverted : T_ULARGE_INTEGER;       // 转换结果（写入 ADS Raw 报文）\n    bConvert     : BOOL;                   // 在线置 TRUE 触发一次转换",
    demo_call="IF bConvert AND lrSetpoint >= 0 THEN\n    // 上升沿触发：先校验非负，避免命中 PDF 未定义行为\n    uliConverted := LREAL_TO_UINT64(lrSetpoint);\n    bConvert := FALSE;\nEND_IF;",
)

_add("LWORD_TO_ULARGE",
    subdir="uint64", section="4.9.2", ret=ULI,
    inputs=[("in","LWORD","-","待转换的 TwinCAT 3 原生 64 位无符号值")],
    in_out=[],
    purpose="把 TwinCAT 3 原生的 `LWORD`（64 位无符号位串）按位重新打包成 TwinCAT 2 旧式 `T_ULARGE_INTEGER` 结构体。便于把 TC3 代码里的 64 位寄存器值喂给只接受 legacy 类型的旧库函数。",
    behavior="本函数只是把 64 位的 LWORD 按高 32 位写入 dwHighPart、低 32 位写入 dwLowPart，不改变数值意义，也没有溢出风险。等价于手写 `result.dwHighPart := DWORD(SHR(in, 32)); result.dwLowPart := DWORD(in);`，但避免读者反复确认位移方向。在与 ADS 报文中按 T_ULARGE_INTEGER 描述的 8 字节字段交互时常用。",
    ret_doc="`T_ULARGE_INTEGER` —— 与 `in` 数值完全相等的结构体表示。",
    pitfalls=[
        "纯位串重打包：不丢精度，但也不做端序转换；wire 上来的大端字节流必须先 `BE64_TO_HOST` 之类处理",
        "把转换结果当 ULINT 用前需调 `ULARGE_TO_ULINT`，直接看 dwHighPart/dwLowPart 容易看错",
        "传入 LWORD 表达式时注意优先级，例如 `LWORD_TO_ULARGE(a OR b)` 比拆开两行更清晰",
    ],
    scenario="把硬件计数器累计值（64 位寄存器读回的 LWORD）写入一个按 T_ULARGE_INTEGER 定义的报警阈值结构体里。",
    value="替代手写两次位移与 DWORD 强转；函数语义清晰，单元测试覆盖一行就够。",
    demo_vars="lwTickCount  : LWORD := 16#FEDCBA9876543210;   // 硬件计数器读回值\n    uliResult    : T_ULARGE_INTEGER;                  // 重打包后的结构体\n    bRepack      : BOOL;                              // 在线触发",
    demo_call="IF bRepack THEN\n    // 数值不变只换表示形式，无须额外校验\n    uliResult := LWORD_TO_ULARGE(lwTickCount);\n    bRepack := FALSE;\nEND_IF;",
)

_add("STRING_TO_UINT64",
    subdir="uint64", section="4.9.3", ret=ULI,
    inputs=[("in","STRING(21)","-","待转换的字符串；最长 21 字符（2⁶⁴−1 = 18446744073709551615 共 20 位 + 终止符）")],
    in_out=[],
    purpose="把十进制字符串解析为 TwinCAT 2 旧式无符号 64 位整数 `T_ULARGE_INTEGER`。常用于把 HMI 输入框或文本文件里读到的大整数字符串还原为 PLC 可算术运算的二进制表示。",
    behavior="函数从左到右扫描 `STRING(21)`，按 ASCII '0'..'9' 累加进 64 位累加器；遇到非数字字符或长度溢出时 PDF 未定义结果 ⚠️。最大支持值为 2⁶⁴−1，对应字符串 \'18446744073709551615\'。负号、十六进制前缀（0x）、千位分隔符、空白均不被解析。空字符串返回 0。STRING 容量 21 已为最大 20 位数字 + 结尾留 1，足够；如果输入来自 STRING(80) 也兼容（只读到前 21 字节）。",
    ret_doc="`T_ULARGE_INTEGER` —— 解析后的 64 位整数；解析失败时 PDF 未列错误码 ⚠️，调用方应在调用前用 `F_IsValidDecimalString` 之类的辅助函数校验。",
    pitfalls=[
        "非法字符 / 超长 / 负号 PDF 未定义结果 ⚠️ —— 调用前必须自检",
        "字符串末尾的空白或回车会终止扫描（按 ASCII 0..9 判断），不会自动 trim",
        "结果是 legacy 结构体；要继续算术请配合 `ULARGE_TO_ULINT`",
        "HMI 输入框常带 LF/CR/空格，建议先 `F_LTrim` + `F_RTrim`",
    ],
    scenario="从 CSV 报表读到的产量计数字符串还原为 64 位整数用于累加。",
    value="替代手写 `WHILE i &lt;= LEN(s) DO ... END_WHILE` 累加循环；一次调用搞定，错误风险集中在校验上而不是解析上。",
    demo_vars="sCountText   : STRING(21) := '18446744073709551615';   // 来自 CSV 报表的极大值\n    uliCount     : T_ULARGE_INTEGER;                          // 解析后的整数\n    bParse       : BOOL;                                      // 触发一次解析",
    demo_call="IF bParse THEN\n    // 上升沿触发：实际工程应先用 F_IsValidDecimalString 校验\n    uliCount := STRING_TO_UINT64(sCountText);\n    bParse := FALSE;\nEND_IF;",
)

_add("UInt32x32To64",
    subdir="uint64", section="4.9.4", ret=ULI,
    inputs=[("ui32a","DWORD","-","乘数 A（32 位无符号）"),
            ("ui32b","DWORD","-","乘数 B（32 位无符号）")],
    in_out=[],
    purpose="把两个 32 位无符号整数相乘，乘积以 64 位 `T_ULARGE_INTEGER` 返回。专门用于'两个 32 位相乘会溢出 32 位'的场景，避免手写时把结果截断到 32 位。",
    behavior="本函数对两个 DWORD 做硬件级 32×32→64 乘法（x86 的 MUL EAX 指令、ARM 的 UMULL 指令一条搞定），结果范围 0..(2³²−1)² ≈ 1.8E19，不会溢出 64 位。任何输入组合都安全，包括两个 0xFFFFFFFF。结果先看 dwHighPart 是否为 0：若为 0，乘积可直接当 DWORD 用；不为 0 时必须当 64 位看待。",
    ret_doc="`T_ULARGE_INTEGER` —— 真正的 64 位乘积，永远不溢出。",
    pitfalls=[
        "不要直接写 `DWORD(a) * DWORD(b)` —— TwinCAT 会按 32 位截断，丢高位",
        "结果若要继续乘加，先 `ULARGE_TO_ULINT` 转 ULINT 更顺手",
        "两输入都是无符号；负的 DINT 必须先 `DINT_TO_DWORD` 显式转换并理解位模式含义",
        "在 32 位 CPU 上单条指令完成，性能与一次 DWORD 乘法相当",
    ],
    scenario="计算两个 32 位计数器（如周期计数 × 单周期事件数）相乘后的总事件数，可能超过 32 位上限。",
    value="替代手写 32×32 → 64 位的双倍长乘法；一行调用，性能等同于硬件单指令。",
    demo_vars="dwCycleCount : DWORD := 16#FFFFFFFF;   // 接近 32 位上限的周期数\n    dwPerCycle   : DWORD := 100;             // 每周期事件数\n    uliTotal     : T_ULARGE_INTEGER;          // 64 位乘积\n    bCompute     : BOOL;                     // 触发计算",
    demo_call="IF bCompute THEN\n    // 上升沿触发：避免反复算（PLC 周期内只调用一次）\n    uliTotal := UInt32x32To64(dwCycleCount, dwPerCycle);\n    bCompute := FALSE;\nEND_IF;",
)

_add("UINT64_TO_LREAL",
    subdir="uint64", section="4.9.5", ret="LREAL",
    inputs=[("in",ULI,"-","待转换的 64 位无符号整数")],
    in_out=[],
    purpose="把 TwinCAT 2 旧式 `T_ULARGE_INTEGER`（结构体）转换为 LREAL 浮点数，用于人机界面显示、报表导出或与浮点算法（如 PID）接口。",
    behavior="函数把 dwHighPart × 2³² + dwLowPart 计算为一个 LREAL。LREAL 尾数 52 位（IEEE 754 双精度），所以小于 2⁵³ (≈ 9.007E15) 的整数可精确表达；2⁵³..2⁶⁴ 区间的值会丢精度，最低几位被舍入到最近的偶数（IEEE 754 默认 round-to-nearest-even）。本函数不报错、不抛异常；超过精度阈值只是结果不再'位级精确'。当需要'既要显示也要做精确算术'时，应把 LREAL 仅作显示，算术继续在 `T_ULARGE_INTEGER` 上做。",
    ret_doc="`LREAL` —— 数值上等于 `in`，但大于 2⁵³ 时只是最近的浮点近似。",
    pitfalls=[
        "大于 2⁵³ 时丢精度（被四舍五入到偶数尾数）",
        "不要把 LREAL 再转回 `T_ULARGE_INTEGER` 后跟原始值比较；可能不相等",
        "用于 HMI 显示时通常无影响；用于算术请保持在整数域",
        "无 NaN / Inf 风险（输入是有界整数）",
    ],
    scenario="HMI 上要显示电表累计电度（64 位计数器），需要换成 LREAL 才能让 TPY 上的浮点显示控件正确处理小数位与单位换算。",
    value="替代手写 `LREAL(in.dwHighPart) * 4294967296.0 + LREAL(in.dwLowPart)`；一行调用，可读性更高。",
    demo_vars="uliEnergy    : T_ULARGE_INTEGER;       // 累计电度（来自电表通讯）\n    lrEnergyKWh  : LREAL;                  // HMI 显示用浮点\n    bConvert     : BOOL;                   // 触发一次转换",
    demo_call="IF bConvert THEN\n    // 仅用于显示；精确算术保持在 T_ULARGE_INTEGER 域内\n    lrEnergyKWh := UINT64_TO_LREAL(uliEnergy);\n    bConvert := FALSE;\nEND_IF;",
)

_add("UINT64_TO_STRING",
    subdir="uint64", section="4.9.6", ret="STRING(21)",
    inputs=[("in",ULI,"-","待格式化为十进制字符串的 64 位无符号整数")],
    in_out=[],
    purpose="把 TwinCAT 2 旧式 `T_ULARGE_INTEGER` 格式化为十进制字符串，便于在 HMI、CSV 报表、日志中显示。最大 20 位数字（2⁶⁴−1 = 18446744073709551615），加结尾零共 21 字节，匹配 `STRING(21)` 容量。",
    behavior="函数对 `in.dwHighPart * 2³² + in.dwLowPart` 做反复除 10 取余，得到反向的十进制字符序列，再翻转写入返回 STRING。没有千位分隔符、没有前导零、没有正号；输入为 0 时返回 \'0\'。整段计算无内部状态、单 PLC 周期完成。",
    ret_doc="`STRING(21)` —— 十进制表示，无前导零、无正负号；0..18446744073709551615 字符串长度 1..20。",
    pitfalls=[
        "若把结果再写入更小的 STRING(10) 等容器会被截断，建议保留 STRING(21) 或更大",
        "需要十六进制？用 `LWORD_TO_HEXSTR(ULARGE_TO_LWORD(in))` 组合",
        "没有千位分隔；HMI 显示分隔符需要二次格式化",
    ],
    scenario="把 64 位数据包计数器导出到 CSV 行，需要先转字符串。",
    value="替代手写 64 位除 10 取余循环；一行调用，无精度损失。",
    demo_vars="uliCounter   : T_ULARGE_INTEGER;       // 64 位数据包计数器\n    sCounterText : STRING(21);             // CSV 列输出\n    bFormat      : BOOL;                   // 触发一次格式化",
    demo_call="IF bFormat THEN\n    // 上升沿触发一次格式化，避免每个周期重做\n    sCounterText := UINT64_TO_STRING(uliCounter);\n    bFormat := FALSE;\nEND_IF;",
)

_add("UInt64Add64",
    subdir="uint64", section="4.9.7", ret=ULI,
    inputs=[("ui64a",ULI,"-","加数 A"),
            ("ui64b",ULI,"-","加数 B")],
    in_out=[],
    purpose="两个 `T_ULARGE_INTEGER` 无符号 64 位整数相加，**不检测溢出**。如需检测溢出请改用 `UInt64Add64Ex`。",
    behavior="函数对两个 64 位结构体做无符号加法。当真实数值之和 ≥ 2⁶⁴ 时按模 2⁶⁴ 截断（wrap-around，等价于 C 语言 unsigned 加法语义）；调用方拿不到任何溢出指示。例如 `ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF) + ULARGE_INTEGER(0, 1)` 返回 `ULARGE_INTEGER(0, 0)`。该截断行为在长时间计数器（如纳秒级 64 位时钟）里通常是有用的；在求差或求和有溢出风险的场景（金额累加、生产量累加）必须改用 Ex 版本。",
    ret_doc="`T_ULARGE_INTEGER` —— `(ui64a + ui64b) mod 2⁶⁴`，无溢出标志。",
    pitfalls=[
        "**静默 wrap-around**：和 ≥ 2⁶⁴ 时被截断，调用方无从感知 → 累加金额慎用",
        "需要溢出指示请用 `UInt64Add64Ex`（多一个 `bOV` VAR_IN_OUT）",
        "重复调用做累加时建议把上一周期的结果 latch 保存，本函数无内部状态",
        "结果是结构体；继续做条件比较请用 `UInt64Cmp64` 而不是 `=`",
    ],
    scenario="纳秒级 64 位时间戳累加：累计运行时间从 0 累加，2⁶⁴ ns ≈ 584 年才会回绕，工程上视为永不溢出。",
    value="替代手写双倍长加法（先低 32 位加 + 进位、再高 32 位加）的两行汇编风格代码；一次调用，可读性更高。",
    demo_vars="uliRuntime   : T_ULARGE_INTEGER;       // 64 位运行时长（ns）累加器\n    uliDelta     : T_ULARGE_INTEGER;       // 本周期增量\n    bAccumulate  : BOOL;                   // 在线触发一次累加",
    demo_call="IF bAccumulate THEN\n    // 静默 wrap-around：纳秒计数 2⁶⁴ ns ≈ 584 年才回绕，工程上忽略\n    uliRuntime := UInt64Add64(uliRuntime, uliDelta);\n    bAccumulate := FALSE;\nEND_IF;",
)

_add("UInt64Add64Ex",
    subdir="uint64", section="4.9.8", ret=ULI,
    inputs=[("augend",ULI,"-","被加数"),
            ("addend",ULI,"-","加数")],
    in_out=[("bOV","BOOL","-","算术溢出标志：TRUE = 溢出，FALSE = 无溢出（调用方必须每周期初始化为 FALSE）")],
    purpose="带溢出检测的 64 位无符号加法。当真实和 ≥ 2⁶⁴ 时仍按 wrap-around 返回结构体，但同时把 `bOV` 置 TRUE，让调用方决定是饱和、报警还是抛错。",
    behavior="函数行为与 `UInt64Add64` 完全一致（同样按模 2⁶⁴ 截断），区别在于 VAR_IN_OUT 的 `bOV` 标志：发生溢出时函数把 `bOV` 设为 TRUE，未溢出时设为 FALSE。**重要**：`bOV` 是 VAR_IN_OUT 引用变量；下一次调用前如果不显式重置，旧值会被覆盖（OK），但如果在多处函数共享一个 `bOV`，应该在每个 PLC 周期开始处统一清零以避免跨周期残留。返回值始终是 wrap-around 的低 64 位，需要饱和效果须自行根据 `bOV` 切换到 2⁶⁴−1。",
    ret_doc="`T_ULARGE_INTEGER` —— 低 64 位和；溢出与否由 `bOV` 反映。",
    pitfalls=[
        "`bOV` 是 VAR_IN_OUT，每周期开始处先清零再调用，避免跨周期残留",
        "调用方需自行处理饱和：`IF bOV THEN result := ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF); END_IF;`",
        "性能略低于无 Ex 版本（多一条比较），但可忽略",
        "VAR_IN_OUT 引用类型变量必须能取地址（即真实左值），不能传立即常量",
    ],
    scenario="金额累加（10⁻⁶ 分单位）需要检测溢出报警，避免长期累计静默回绕。",
    value="替代手写比较 `IF a &gt; (MAX - b) THEN bOV := TRUE; END_IF;` 一段；调用一次同时拿到和与溢出位。",
    demo_vars="uliMoneyAccum : T_ULARGE_INTEGER;     // 累计金额（10⁻⁶ 分）\n    uliMoneyAdd   : T_ULARGE_INTEGER;     // 本笔金额\n    bOverflow     : BOOL;                 // 溢出报警标志\n    bAccumulate   : BOOL;                 // 触发一次累加",
    demo_call="// 周期开始处清零溢出标志，避免上周期残留误报\nbOverflow := FALSE;\nIF bAccumulate THEN\n    uliMoneyAccum := UInt64Add64Ex(uliMoneyAccum, uliMoneyAdd, bOverflow);\n    IF bOverflow THEN\n        // 工程响应：饱和到上限 + 触发报警（业务层处理）\n        uliMoneyAccum := ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF);\n    END_IF;\n    bAccumulate := FALSE;\nEND_IF;",
)

_add("UInt64And",
    subdir="uint64", section="4.9.9", ret=ULI,
    inputs=[("ui64a",ULI,"-","操作数 A"),
            ("ui64b",ULI,"-","操作数 B")],
    in_out=[],
    purpose="两个 `T_ULARGE_INTEGER` 的按位与（AND）。常用于 64 位掩码屏蔽。",
    behavior="函数对 dwHighPart 与 dwHighPart、dwLowPart 与 dwLowPart 分别做 AND 后封装回结构体。位运算无溢出、无副作用、无错误码、单周期完成。常见用法：用 `ULARGE_INTEGER(0, 16#FF)` 做掩码取低 8 位；用 `ULARGE_INTEGER(16#FFFFFFFF, 16#00000000)` 取高 32 位等。",
    ret_doc="`T_ULARGE_INTEGER` —— 按位与结果，与位掩码同表示形式。",
    pitfalls=[
        "掩码必须也是 `T_ULARGE_INTEGER` 类型；常量请用 `ULARGE_INTEGER(high, low)` 构造",
        "若只关心是否有任一位被置位，结合 `UInt64isZero` 判断结果即可",
        "想取某段位的整数值，AND 后还需 `UInt64Shr` 右移",
        "性能：两个 DWORD AND，等价于一条指令",
    ],
    scenario="ADS Raw 报文里把状态寄存器的 64 位状态位按掩码取出特定子位段（如故障码低 16 位）。",
    value="替代分别 AND 高低 DWORD 两行；语义更清晰。",
    demo_vars="uliStatus    : T_ULARGE_INTEGER;       // 状态寄存器（64 位）\n    uliMask      : T_ULARGE_INTEGER;       // 掩码：低 16 位\n    uliFaultCode : T_ULARGE_INTEGER;       // 屏蔽后的故障码\n    bMaskNow     : BOOL;                   // 触发屏蔽",
    demo_call="uliMask := ULARGE_INTEGER(0, 16#0000FFFF);   // 取低 16 位的掩码\nIF bMaskNow THEN\n    uliFaultCode := UInt64And(uliStatus, uliMask);\n    bMaskNow := FALSE;\nEND_IF;",
)

_add("UInt64Cmp64",
    subdir="uint64", section="4.9.10", ret="DINT",
    inputs=[("ui64a",ULI,"-","左操作数；返回 -1 表示 ui64a 小于 ui64b"),
            ("ui64b",ULI,"-","右操作数")],
    in_out=[],
    purpose="比较两个 `T_ULARGE_INTEGER`，返回 -1 / 0 / 1 三态结果，对应小于 / 等于 / 大于。结构体 `=` 比较在 IEC 里不可靠，必须用这个函数。",
    behavior="函数先比较 dwHighPart，相等再比较 dwLowPart。返回 `-1` (ui64a &lt; ui64b)、`0` (ui64a = ui64b)、`1` (ui64a &gt; ui64b)。无符号比较语义：`ULARGE_INTEGER(16#80000000, 0)` &gt; `ULARGE_INTEGER(0, 0)`（最高位置 1 视为正大数，不是负数）。无错误码、无副作用、单周期完成。",
    ret_doc="`DINT` —— `-1` / `0` / `1`，对应小于 / 等于 / 大于。",
    pitfalls=[
        "返回 DINT 不是 BOOL；分支判断用 `IF UInt64Cmp64(a, b) &lt; 0 THEN`",
        "**不要用结构体 `a = b` 直接比较**：IEC 对结构体 `=` 未规定行为；要等于判断请用 `UInt64Cmp64(a, b) = 0`",
        "无符号语义，没有负数概念；从 DINT/LINT 转来的负值实际是大数",
        "排序场景可直接喂给 STL/链表排序回调",
    ],
    scenario="把两个生产批次的产量计数器排序，决定哪条线产量更高。",
    value="替代手写两次 DWORD 比较 + 嵌套 IF；一次调用 + DINT 比较一目了然。",
    demo_vars="uliBatchA    : T_ULARGE_INTEGER;       // A 线产量\n    uliBatchB    : T_ULARGE_INTEGER;       // B 线产量\n    diResult     : DINT;                   // 比较结果\n    bCompare     : BOOL;                   // 触发比较",
    demo_call="IF bCompare THEN\n    // -1: A 少 / 0: 持平 / 1: A 多\n    diResult := UInt64Cmp64(uliBatchA, uliBatchB);\n    bCompare := FALSE;\nEND_IF;",
)

_add("UInt64Div16Ex",
    subdir="uint64", section="4.9.11", ret=ULI,
    inputs=[("dividend",ULI,"-","被除数"),
            ("divisor","WORD","-","除数（16 位无符号）")],
    in_out=[("remainder",ULI,"-","余数（输出）；调用方需要传一个左值变量来接收")],
    purpose="64 位无符号被除数除以 16 位无符号除数，返回商（`T_ULARGE_INTEGER`），余数通过 VAR_IN_OUT `remainder` 输出。专为'被除数远大于除数、商不会回退到几乎全 0'的场景做硬件加速优化。",
    behavior="函数在底层使用 32×64→64 除法或 16×64→64 除法序列。商 = `dividend / divisor`（向零截断），余数 = `dividend mod divisor`（始终 0..divisor-1）。当 `divisor = 0` 时 PDF 未定义结果 ⚠️（实际可能触发硬件异常或返回 0），**调用前必须自检**。`remainder` 即便是 VAR_IN_OUT 也会被函数完全覆盖，调用前无须初始化。",
    ret_doc="`T_ULARGE_INTEGER` —— 商；`remainder` 输出余数。",
    pitfalls=[
        "**除以 0 PDF 未定义** ⚠️ —— 调用前必加 `IF divisor &lt;&gt; 0 THEN ... END_IF;`",
        "余数是 VAR_IN_OUT，参数侧必须能取地址；常量不行",
        "向零截断（与 C/C++ unsigned 除法一致），不是四舍五入",
        "性能比 `UInt64Div64Ex` 略快（除数只有 16 位）；若除数动态超过 65535 改用 64-bit 版",
    ],
    scenario="64 位时钟戳（ns）除以 1000 转毫秒、再除以 1000 转秒等小除数链。",
    value="替代手写 64 位除法链；硬件指令一次搞定，性能可预测。",
    demo_vars="uliNanos     : T_ULARGE_INTEGER;       // 纳秒时间戳\n    wDivider     : WORD := 1000;           // 转毫秒的除数\n    uliMillis    : T_ULARGE_INTEGER;       // 商：毫秒数\n    uliRemainder : T_ULARGE_INTEGER;       // 余数：剩余纳秒\n    bDivide      : BOOL;",
    demo_call="IF bDivide AND wDivider <> 0 THEN\n    // 除 0 PDF 未定义 → 前置校验\n    uliMillis := UInt64Div16Ex(uliNanos, wDivider, uliRemainder);\n    bDivide := FALSE;\nEND_IF;",
)

_add("UInt64Div64",
    subdir="uint64", section="4.9.12", ret=ULI,
    inputs=[("dividend",ULI,"-","被除数"),
            ("divisor",ULI,"-","除数")],
    in_out=[],
    purpose="两个 64 位无符号整数相除，返回商。仅返回商不返回余数；要余数请改用 `UInt64Mod64`，或选 `UInt64Div64Ex`（同时给商和余数）。",
    behavior="商 = `dividend / divisor`（向零截断）。当 `divisor = 0` 时 PDF 未定义结果 ⚠️，必须前置校验。函数无内部状态、单周期完成、性能取决于硬件 64 位除法指令（x86-64 单条 DIV，约 20-100 周期，比加减慢）。",
    ret_doc="`T_ULARGE_INTEGER` —— 整数商，向零截断。",
    pitfalls=[
        "**除以 0 PDF 未定义** ⚠️",
        "丢失余数 —— 余数信息要用 `UInt64Mod64` 单独求或改用 Ex 版本",
        "向零截断不是四舍五入；19/10 = 1，−19 在无符号语义下不存在",
        "性能比加法慢一个数量级（一条 DIV 指令），频繁调用时考虑预计算",
    ],
    scenario="把累计字节数 / 周期数 = 平均每周期字节数（吞吐率），用于在 HMI 显示。",
    value="替代手写双倍长除法；一次调用直接拿商。",
    demo_vars="uliTotalBytes: T_ULARGE_INTEGER;       // 累计字节数\n    uliCycles    : T_ULARGE_INTEGER;       // 周期数\n    uliAvgBytes  : T_ULARGE_INTEGER;       // 平均吞吐\n    bCompute     : BOOL;",
    demo_call="IF bCompute AND NOT UInt64isZero(uliCycles) THEN\n    // 除 0 校验：除数是结构体，用 UInt64isZero 不是 = 0\n    uliAvgBytes := UInt64Div64(uliTotalBytes, uliCycles);\n    bCompute := FALSE;\nEND_IF;",
)

_add("UInt64Div64Ex",
    subdir="uint64", section="4.9.13", ret=ULI,
    inputs=[("dividend",ULI,"-","被除数"),
            ("divisor",ULI,"-","除数")],
    in_out=[("remainder",ULI,"-","输出余数；调用方需提供左值变量")],
    purpose="带余数输出的 64 位无符号除法。一次调用同时拿到商（返回值）和余数（VAR_IN_OUT），效率高于'先 Div 再 Mod'的两次调用。",
    behavior="商 = `dividend / divisor` 向零截断；余数 = `dividend - 商 * divisor`，范围 0..divisor-1。`divisor = 0` PDF 未定义。`remainder` 由函数完全覆盖；调用前无须初始化。底层硬件除法指令一次返回商与余数，所以本函数比 `UInt64Div64` + `UInt64Mod64` 快约一倍。",
    ret_doc="`T_ULARGE_INTEGER` —— 商；`remainder` 输出余数。",
    pitfalls=[
        "**除以 0 PDF 未定义** ⚠️",
        "余数是 VAR_IN_OUT，参数侧必须能取地址",
        "已经一次取走余数，不要再二次调 `UInt64Mod64` 重复算",
        "把 `remainder` 当临时变量复用要小心 —— 函数会覆盖原值",
    ],
    scenario="把累计纳秒数同时拆成秒数（商）+ 纳秒余数（亚秒部分）用于显示。",
    value="一次硬件除法同时拿商与余数，比两次调用快一倍。",
    demo_vars="uliNanos     : T_ULARGE_INTEGER;       // 累计纳秒\n    uliDivisor   : T_ULARGE_INTEGER;       // 1e9 = 一秒的纳秒数\n    uliSeconds   : T_ULARGE_INTEGER;       // 秒数（商）\n    uliSubNs     : T_ULARGE_INTEGER;       // 亚秒纳秒（余数）\n    bCompute     : BOOL;",
    demo_call="uliDivisor := ULARGE_INTEGER(0, 1000000000);   // 1e9\nIF bCompute AND NOT UInt64isZero(uliDivisor) THEN\n    uliSeconds := UInt64Div64Ex(uliNanos, uliDivisor, uliSubNs);\n    bCompute := FALSE;\nEND_IF;",
)

_add("UInt64isZero",
    subdir="uint64", section="4.9.14", ret="BOOL",
    inputs=[("ui64",ULI,"-","待判定的 64 位无符号整数")],
    in_out=[],
    purpose="判断 `T_ULARGE_INTEGER` 是否为 0。结构体 `=` 比较不可靠，必须用本函数（或 `UInt64Cmp64(x, ULARGE_INTEGER(0,0)) = 0`）。",
    behavior="函数检查 `ui64.dwHighPart = 0 AND ui64.dwLowPart = 0`，是则返回 TRUE，否则返回 FALSE。无副作用、单周期。常用于除法前判 0、累加结束判 0、空状态判断。",
    ret_doc="`BOOL` —— TRUE = 整数为 0；FALSE = 任一位置 1。",
    pitfalls=[
        "**不要写 `x = 0`** —— `0` 是 INT 字面量，与 T_ULARGE_INTEGER 类型不兼容，编译可能报错也可能匹配错误重载",
        "判 0 后做除法仍要小心被除数为 0 的情形：除以 0 才是问题，被除数为 0 商也为 0",
        "本函数是 FC，无内部状态；放在 IF 条件里反复调用也无开销问题",
    ],
    scenario="除法前校验除数，避免除 0 PDF 未定义。",
    value="替代结构体 `=` 比较（在某些 TwinCAT 版本里不可靠或语义不明）。",
    demo_vars="uliDivisor   : T_ULARGE_INTEGER;       // 除数\n    bIsZero      : BOOL;                   // 是否为 0\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    // 除法前的合法性校验\n    bIsZero := UInt64isZero(uliDivisor);\n    bCheck := FALSE;\nEND_IF;",
)

_add("UInt64Limit",
    subdir="uint64", section="4.9.15", ret=ULI,
    inputs=[("ui64min",ULI,"-","下界"),
            ("ui64in",ULI,"-","待限幅的输入"),
            ("ui64max",ULI,"-","上界")],
    in_out=[],
    purpose="对 64 位无符号整数做上下限限幅（saturate）：低于 `ui64min` 返回 `ui64min`，高于 `ui64max` 返回 `ui64max`，否则返回 `ui64in`。等价于 `MAX(ui64min, MIN(ui64in, ui64max))`，但一次调用更易读。",
    behavior="函数先与下界比较再与上界比较，分支选择三态结果。要求 `ui64min ≤ ui64max`；若调用方传入颠倒的边界，PDF 未定义 ⚠️。无副作用、单周期。常用于工业设定值限幅（如电机速度上限）、ADS 数据回写前的安全裁剪、HMI 输入范围保护。",
    ret_doc="`T_ULARGE_INTEGER` —— 裁剪后的值，保证落在 [ui64min, ui64max]。",
    pitfalls=[
        "**调用方必须保证 `ui64min ≤ ui64max`** ⚠️ —— PDF 没说颠倒时行为",
        "无符号语义，没有负边界",
        "如果 `ui64min = 0` 且 `ui64max = MAX64`，函数永远返回 `ui64in`（恒等）",
        "实际生产中常包一层 FB，把 min/max 当常量配置项",
    ],
    scenario="HMI 操作员输入电机转速设定值，必须裁剪到机械允许的最大转速 5000 rpm = 5000，最小 100。",
    value="替代手写两次 `UInt64Cmp64` + 嵌套 IF；一次调用语义清晰。",
    demo_vars="uliRpmMin    : T_ULARGE_INTEGER;       // 转速下限 100\n    uliRpmMax    : T_ULARGE_INTEGER;       // 转速上限 5000\n    uliHmiInput  : T_ULARGE_INTEGER;       // 操作员输入\n    uliRpmSafe   : T_ULARGE_INTEGER;       // 限幅后\n    bLimit       : BOOL;",
    demo_call="uliRpmMin := ULARGE_INTEGER(0, 100);\nuliRpmMax := ULARGE_INTEGER(0, 5000);\nIF bLimit THEN\n    // 防止操作员误输入超界值打坏机械\n    uliRpmSafe := UInt64Limit(uliRpmMin, uliHmiInput, uliRpmMax);\n    bLimit := FALSE;\nEND_IF;",
)

_add("UInt64Max",
    subdir="uint64", section="4.9.16", ret=ULI,
    inputs=[("ui64a",ULI,"-","操作数 A"),
            ("ui64b",ULI,"-","操作数 B")],
    in_out=[],
    purpose="返回两个 `T_ULARGE_INTEGER` 中较大的一个（无符号比较）。",
    behavior="函数等价于 `IF UInt64Cmp64(a, b) > 0 THEN RETURN a; ELSE RETURN b; END_IF`，但用一次调用完成、可在表达式位置。无符号语义；最高位置 1 的值视为大正数，不是负数。无副作用、单周期。",
    ret_doc="`T_ULARGE_INTEGER` —— `a` 与 `b` 中较大者；相等时返回 `b`（实际等价）。",
    pitfalls=[
        "无符号比较，不要把 LARGE/LINT 转来的负数当负看",
        "需要三路比较请连续调用 `UInt64Max(a, UInt64Max(b, c))`",
        "性能等价于一次 `UInt64Cmp64`，可放表达式位置",
    ],
    scenario="多路温度传感器读回 64 位计数，取最大值做超温报警阈值比对。",
    value="替代手写比较 + 选择；一次调用，可读性更高。",
    demo_vars="uliA         : T_ULARGE_INTEGER;       // 传感器 A 计数\n    uliB         : T_ULARGE_INTEGER;       // 传感器 B 计数\n    uliMax       : T_ULARGE_INTEGER;       // 较大者\n    bPick        : BOOL;",
    demo_call="IF bPick THEN\n    uliMax := UInt64Max(uliA, uliB);\n    bPick := FALSE;\nEND_IF;",
)

_add("UInt64Min",
    subdir="uint64", section="4.9.17", ret=ULI,
    inputs=[("ui64a",ULI,"-","操作数 A"),
            ("ui64b",ULI,"-","操作数 B")],
    in_out=[],
    purpose="返回两个 `T_ULARGE_INTEGER` 中较小的一个（无符号比较）。",
    behavior="函数等价于 `IF UInt64Cmp64(a, b) < 0 THEN RETURN a; ELSE RETURN b; END_IF`，单次调用、表达式位置可用。无符号语义、单周期。",
    ret_doc="`T_ULARGE_INTEGER` —— `a` 与 `b` 中较小者。",
    pitfalls=[
        "PDF 在描述里把 T_ULARGE_INTEGER 误写成 T_ULARGE_INEGER（已确认是排版错），不影响实际语义",
        "无符号比较",
        "需要三路 min 请嵌套调用",
    ],
    scenario="选定两个生产线的剩余容量中较小者作为系统瓶颈。",
    value="替代手写 IF/ELSE；一次调用。",
    demo_vars="uliLineA     : T_ULARGE_INTEGER;       // A 线剩余\n    uliLineB     : T_ULARGE_INTEGER;       // B 线剩余\n    uliMin       : T_ULARGE_INTEGER;       // 瓶颈\n    bPick        : BOOL;",
    demo_call="IF bPick THEN\n    uliMin := UInt64Min(uliLineA, uliLineB);\n    bPick := FALSE;\nEND_IF;",
)

_add("UInt64Mod64",
    subdir="uint64", section="4.9.18", ret=ULI,
    inputs=[("dividend",ULI,"-","被除数"),
            ("divisor",ULI,"-","除数")],
    in_out=[],
    purpose="64 位无符号模运算：返回 `dividend mod divisor`。仅取余不取商；要同时拿商和余请用 `UInt64Div64Ex`。",
    behavior="结果 = `dividend - (dividend / divisor) * divisor`，范围 0..divisor-1。`divisor = 0` PDF 未定义 ⚠️。常用于循环索引（计数器 mod N）、哈希分桶、时间戳取亚秒部分。",
    ret_doc="`T_ULARGE_INTEGER` —— 余数。",
    pitfalls=[
        "**除以 0 PDF 未定义** ⚠️",
        "已经求余就不要再做一次 `UInt64Div64` 求商：用 Ex 版本一次拿走两个",
        "余数始终非负（无符号语义）",
    ],
    scenario="64 位累计事件计数 mod N（N = 缓冲区大小）得到环形缓冲区写指针。",
    value="替代手写 `dividend - 商 * divisor`；一次调用避免中间变量。",
    demo_vars="uliCounter   : T_ULARGE_INTEGER;       // 累计事件计数\n    uliBufSize   : T_ULARGE_INTEGER;       // 环形缓冲区大小\n    uliIndex     : T_ULARGE_INTEGER;       // 写入索引\n    bIndex       : BOOL;",
    demo_call="uliBufSize := ULARGE_INTEGER(0, 1024);\nIF bIndex AND NOT UInt64isZero(uliBufSize) THEN\n    uliIndex := UInt64Mod64(uliCounter, uliBufSize);\n    bIndex := FALSE;\nEND_IF;",
)

_add("UInt64Mul64",
    subdir="uint64", section="4.9.19", ret=ULI,
    inputs=[("multiplicand",ULI,"-","被乘数"),
            ("multiplier",ULI,"-","乘数")],
    in_out=[],
    purpose="两个 64 位无符号整数相乘，**不检测溢出**。要溢出检测请改用 `UInt64Mul64Ex`。",
    behavior="函数返回真实积的低 64 位（即按模 2⁶⁴ 截断的 wrap-around 结果）。当真实积 ≥ 2⁶⁴ 时高位被静默丢弃。例如 `2^33 * 2^33 = 2^66` 返回 0。底层硬件 64×64→64 乘法指令一次完成（x86-64 MUL，几个周期）。",
    ret_doc="`T_ULARGE_INTEGER` —— `(a * b) mod 2⁶⁴`，无溢出指示。",
    pitfalls=[
        "**静默 wrap-around** —— 任一操作数 > 2³² 都有溢出风险，应改用 Ex 版本",
        "如果只是 32×32→64，更省心的是 `UInt32x32To64`（永不溢出）",
        "性能：一条硬件指令",
    ],
    scenario="低位 32 位以下的两个计数器相乘（确认不会溢出）求合并指标。",
    value="替代 Ex 版本在已知安全的快路径上节省一个 VAR_IN_OUT 参数。",
    demo_vars="uliA         : T_ULARGE_INTEGER;       // 操作数\n    uliB         : T_ULARGE_INTEGER;       // 操作数\n    uliProduct   : T_ULARGE_INTEGER;       // 乘积\n    bMultiply    : BOOL;",
    demo_call="IF bMultiply THEN\n    // 调用方已确保不溢出 → 跳过 Ex 版本的检测开销\n    uliProduct := UInt64Mul64(uliA, uliB);\n    bMultiply := FALSE;\nEND_IF;",
)

_add("UInt64Mul64Ex",
    subdir="uint64", section="4.9.20", ret=ULI,
    inputs=[("multiplicand",ULI,"-","被乘数"),
            ("multiplier",ULI,"-","乘数")],
    in_out=[("bOV","BOOL","-","算术溢出标志：TRUE = 溢出（每周期需先清零）")],
    purpose="带溢出检测的 64 位无符号乘法。乘积仍按模 2⁶⁴ 返回，但同时把 `bOV` 置 TRUE 让调用方决定饱和、报警或抛错。",
    behavior="底层通常用 64×64→128 位乘法指令，检测高 64 位是否非零来判溢出，再返回低 64 位。`bOV` 是 VAR_IN_OUT，每周期开始处建议先清零避免跨周期残留。`bOV = TRUE` 时返回值仍是低 64 位，调用方需手动饱和到 `MAX64`。",
    ret_doc="`T_ULARGE_INTEGER` —— 低 64 位积；`bOV` 反映溢出。",
    pitfalls=[
        "`bOV` 每周期开始处清零",
        "饱和需调用方实现：`IF bOV THEN result := ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF); END_IF;`",
        "VAR_IN_OUT 不可传立即值",
        "性能略低于无 Ex 版（多一条比较），可忽略",
    ],
    scenario="计算累计扭矩 × 累计转角，结果可能超 64 位，需溢出报警。",
    value="替代手写'先转 LREAL 估算溢出再走整数路径'的判断；一次调用拿乘积 + 溢出位。",
    demo_vars="uliTorque    : T_ULARGE_INTEGER;\n    uliAngle     : T_ULARGE_INTEGER;\n    uliWork      : T_ULARGE_INTEGER;       // 累计做功\n    bOverflow    : BOOL;                   // 溢出报警\n    bCompute     : BOOL;",
    demo_call="bOverflow := FALSE;                                    // 每周期先清零\nIF bCompute THEN\n    uliWork := UInt64Mul64Ex(uliTorque, uliAngle, bOverflow);\n    IF bOverflow THEN\n        // 工程响应：饱和并触发上层报警\n        uliWork := ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF);\n    END_IF;\n    bCompute := FALSE;\nEND_IF;",
)

_add("UInt64Not",
    subdir="uint64", section="4.9.21", ret=ULI,
    inputs=[("ui64",ULI,"-","操作数")],
    in_out=[],
    purpose="对 `T_ULARGE_INTEGER` 做按位取反。",
    behavior="对 dwHighPart 与 dwLowPart 分别取反并封装回结构体。等价于 XOR 全 1 掩码。用于构造掩码（取反后做 AND 屏蔽某些位）、或翻转所有标志位。",
    ret_doc="`T_ULARGE_INTEGER` —— 按位取反结果。",
    pitfalls=[
        "全 0 取反等于全 1（即 MAX64），可用作构造 MAX 常量的快捷方式",
        "想构造'除了某几位以外全 1'的掩码：`UInt64Not(UInt64Or(...))`",
        "结果仍是结构体，不能直接当 BOOL 用",
    ],
    scenario="构造\'除了 bit0 以外全屏蔽\'的掩码：先 `ULARGE_INTEGER(0,1)` 再 `UInt64Not(...)`。",
    value="替代手写两次 DWORD NOT。",
    demo_vars="uliBitMask   : T_ULARGE_INTEGER;       // 单 bit 掩码\n    uliInverted  : T_ULARGE_INTEGER;       // 取反后\n    bInvert      : BOOL;",
    demo_call="uliBitMask := ULARGE_INTEGER(0, 1);\nIF bInvert THEN\n    uliInverted := UInt64Not(uliBitMask);   // 除了 bit0 之外全 1\n    bInvert := FALSE;\nEND_IF;",
)

_add("UInt64Or",
    subdir="uint64", section="4.9.22", ret=ULI,
    inputs=[("ui64a",ULI,"-","操作数 A"),
            ("ui64b",ULI,"-","操作数 B")],
    in_out=[],
    purpose="两个 `T_ULARGE_INTEGER` 的按位或。用于多个标志位的合并。",
    behavior="对 dwHighPart、dwLowPart 分别 OR 后封装。无副作用、单周期。",
    ret_doc="`T_ULARGE_INTEGER` —— 按位或。",
    pitfalls=[
        "OR 不能撤销已置位的位，要清位用 AND + NOT 组合",
        "构造多个 bit 同时置位时使用 OR 链：`OR(OR(a, b), c)`",
    ],
    scenario="把多个子模块的 64 位故障位合并成系统级故障字。",
    value="替代手写两次 DWORD OR。",
    demo_vars="uliFaultModuleA: T_ULARGE_INTEGER;     // 模块 A 故障字\n    uliFaultModuleB: T_ULARGE_INTEGER;     // 模块 B 故障字\n    uliFaultSys    : T_ULARGE_INTEGER;     // 系统总故障字\n    bMerge         : BOOL;",
    demo_call="IF bMerge THEN\n    uliFaultSys := UInt64Or(uliFaultModuleA, uliFaultModuleB);\n    bMerge := FALSE;\nEND_IF;",
)

_add("UInt64Rol",
    subdir="uint64", section="4.9.23", ret=ULI,
    inputs=[("ui64",ULI,"-","待循环左移的操作数"),
            ("n","DWORD","-","左移的位数（0..63；超过 64 PDF 未定义）")],
    in_out=[],
    purpose="对 `T_ULARGE_INTEGER` 做循环左移：移出最高位的内容回卷到最低位。常用于哈希函数（如 MurmurHash、CityHash）或加密算法的混淆步骤。",
    behavior="结果 = `(ui64 SHL n) OR (ui64 SHR (64-n))`。n 通常应在 0..63；`n = 0` 等于恒等；`n ≥ 64` PDF 未定义 ⚠️（实践经验多数实现等于 n mod 64，但请勿依赖）。无副作用、单周期。",
    ret_doc="`T_ULARGE_INTEGER` —— 循环左移结果。",
    pitfalls=[
        "**n 应保证在 0..63** ⚠️ —— 超过 PDF 未定义",
        "循环移位**不**丢位（与 Shl 不同：Shl 移出去就丢了）",
        "适合哈希混淆；不适合用作算术 ×2ⁿ",
    ],
    scenario="MurmurHash3 64-bit 实现里 `k = ROTL(k, 31)` 的混淆步骤。",
    value="替代手写 SHL + SHR + OR 三步；一次调用语义清晰。",
    demo_vars="uliHashState : T_ULARGE_INTEGER;       // 哈希中间状态\n    dwShiftBits  : DWORD := 31;            // MurmurHash3 推荐值\n    uliRotated   : T_ULARGE_INTEGER;\n    bRotate      : BOOL;",
    demo_call="IF bRotate AND dwShiftBits < 64 THEN\n    // 必须 n < 64，否则 PDF 未定义\n    uliRotated := UInt64Rol(uliHashState, dwShiftBits);\n    bRotate := FALSE;\nEND_IF;",
)

_add("UInt64Ror",
    subdir="uint64", section="4.9.24", ret=ULI,
    inputs=[("ui64",ULI,"-","待循环右移的操作数"),
            ("n","DWORD","-","右移的位数（0..63；超过 64 PDF 未定义）")],
    in_out=[],
    purpose="对 `T_ULARGE_INTEGER` 做循环右移：移出最低位的内容回卷到最高位。常用于哈希、加密。",
    behavior="结果 = `(ui64 SHR n) OR (ui64 SHL (64-n))`。n 应在 0..63，n=0 恒等，n≥64 PDF 未定义 ⚠️。无副作用。",
    ret_doc="`T_ULARGE_INTEGER` —— 循环右移结果。",
    pitfalls=[
        "**n 应在 0..63** ⚠️",
        "循环移位不丢位",
        "常用搭配 `UInt64Rol` 实现 bit 旋转链",
    ],
    scenario="SHA-256 / SHA-512 风格哈希里的 σ₀ / σ₁ 混淆函数。",
    value="替代 SHR+SHL+OR 三行。",
    demo_vars="uliHashState : T_ULARGE_INTEGER;\n    dwShiftBits  : DWORD := 29;\n    uliRotated   : T_ULARGE_INTEGER;\n    bRotate      : BOOL;",
    demo_call="IF bRotate AND dwShiftBits < 64 THEN\n    uliRotated := UInt64Ror(uliHashState, dwShiftBits);\n    bRotate := FALSE;\nEND_IF;",
)

_add("UInt64Shl",
    subdir="uint64", section="4.9.25", ret=ULI,
    inputs=[("ui64",ULI,"-","待左移的操作数"),
            ("n","DWORD","-","左移的位数")],
    in_out=[],
    purpose="对 `T_ULARGE_INTEGER` 做逻辑左移。移出去的最高位**直接丢弃**，最低位补 0。等价于乘以 2ⁿ（不溢出检测）。",
    behavior="结果 = `ui64 * 2ⁿ mod 2⁶⁴`。n ≥ 64 PDF 未定义 ⚠️（多数实现等于 n mod 64）。常用作 2 的幂次乘法的高效替代。",
    ret_doc="`T_ULARGE_INTEGER` —— 左移结果。",
    pitfalls=[
        "**移出去的位丢失** —— 不是循环移位",
        "n ≥ 64 PDF 未定义 ⚠️",
        "等价于乘以 2ⁿ 但不检测溢出",
    ],
    scenario="把 nanos 转 PicoSec 需要乘 1000，但若是 1024（2¹⁰）可用 `Shl(n, 10)` 加速。",
    value="替代乘法操作，性能更好；与 Shr 配对实现 64 位整数的位级缩放。",
    demo_vars="uliValue     : T_ULARGE_INTEGER;\n    dwShiftBits  : DWORD := 10;\n    uliScaled    : T_ULARGE_INTEGER;       // = value × 2^10 = ×1024\n    bScale       : BOOL;",
    demo_call="IF bScale AND dwShiftBits < 64 THEN\n    uliScaled := UInt64Shl(uliValue, dwShiftBits);\n    bScale := FALSE;\nEND_IF;",
)

_add("UInt64Shr",
    subdir="uint64", section="4.9.26", ret=ULI,
    inputs=[("ui64",ULI,"-","待右移的操作数"),
            ("n","DWORD","-","右移的位数")],
    in_out=[],
    purpose="对 `T_ULARGE_INTEGER` 做逻辑右移。最高位补 0，最低位移出去丢弃。等价于无符号除以 2ⁿ。",
    behavior="结果 = `ui64 / 2ⁿ`（向零截断）。n ≥ 64 PDF 未定义 ⚠️。无符号语义不存在算术右移。",
    ret_doc="`T_ULARGE_INTEGER` —— 右移结果。",
    pitfalls=[
        "**逻辑右移**：高位补 0（无符号无算术右移概念）",
        "n ≥ 64 PDF 未定义 ⚠️",
        "等价无符号除以 2ⁿ，但比 `UInt64Div64` 快得多",
    ],
    scenario="把 64 位寄存器右移取高 32 位作为另一报文字段使用。",
    value="替代除法；性能 1 条指令。",
    demo_vars="uliRegister  : T_ULARGE_INTEGER;       // 64 位寄存器\n    dwShiftBits  : DWORD := 32;\n    uliHigh32    : T_ULARGE_INTEGER;       // 高 32 位\n    bExtract     : BOOL;",
    demo_call="IF bExtract AND dwShiftBits < 64 THEN\n    uliHigh32 := UInt64Shr(uliRegister, dwShiftBits);\n    bExtract := FALSE;\nEND_IF;",
)

_add("UInt64Sub64",
    subdir="uint64", section="4.9.27", ret=ULI,
    inputs=[("ui64a",ULI,"-","被减数"),
            ("ui64b",ULI,"-","减数")],
    in_out=[],
    purpose="两个 `T_ULARGE_INTEGER` 相减。**不检测下溢**：当 `ui64b > ui64a` 时按模 2⁶⁴ 回绕，结果是个非常大的数（类似无符号 C 减法）。",
    behavior="结果 = `(ui64a - ui64b) mod 2⁶⁴`。下溢时静默回绕、无错误码。例如 `ULARGE_INTEGER(0,1) - ULARGE_INTEGER(0,2) = ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF)`。",
    ret_doc="`T_ULARGE_INTEGER` —— 差值，模 2⁶⁴。",
    pitfalls=[
        "**静默下溢**：被减数 < 减数时返回一个非常大的数，调用方必须先用 `UInt64Cmp64` 判 a ≥ b",
        "Tc2_Utilities 没有 Ex 版本检测下溢；要安全减法只能前置比较",
        "金额、时间差等场景务必前置 `UInt64Cmp64(a, b) >= 0` 校验",
    ],
    scenario="算两个 64 位时间戳的差值（ts_end − ts_start），前置校验 end ≥ start 避免回绕。",
    value="替代手写双倍长减法 + 借位；一次调用搞定。",
    demo_vars="uliEnd       : T_ULARGE_INTEGER;       // 结束时间戳\n    uliStart     : T_ULARGE_INTEGER;       // 起始时间戳\n    uliDuration  : T_ULARGE_INTEGER;       // 持续时间\n    bCompute     : BOOL;",
    demo_call="IF bCompute AND UInt64Cmp64(uliEnd, uliStart) >= 0 THEN\n    // 前置校验避免下溢回绕到一个超大数\n    uliDuration := UInt64Sub64(uliEnd, uliStart);\n    bCompute := FALSE;\nEND_IF;",
)

_add("UInt64Xor",
    subdir="uint64", section="4.9.28", ret=ULI,
    inputs=[("ui64a",ULI,"-","操作数 A"),
            ("ui64b",ULI,"-","操作数 B")],
    in_out=[],
    purpose="两个 `T_ULARGE_INTEGER` 的按位异或。常用于状态字差异检测（哪些位发生变化）、加密、奇偶校验。",
    behavior="对 dwHighPart、dwLowPart 分别 XOR 后封装。XOR 的代数性质：`a XOR a = 0`，`a XOR 0 = a`，`a XOR b XOR b = a`（自反性，可用于翻转）。无副作用、单周期。",
    ret_doc="`T_ULARGE_INTEGER` —— 按位异或。",
    pitfalls=[
        "想'哪些位变了'：`XOR(prev, curr)` 得到变化位掩码",
        "翻转某几位：用 OR 1 不行，必须 XOR 掩码",
        "自反性：连续 XOR 同一个数两次还原原值",
    ],
    scenario="检测控制字 64 位中哪些位在本周期发生了翻转。",
    value="替代手写两次 DWORD XOR。",
    demo_vars="uliPrev      : T_ULARGE_INTEGER;       // 上周期状态\n    uliCurr      : T_ULARGE_INTEGER;       // 本周期状态\n    uliDelta     : T_ULARGE_INTEGER;       // 翻转位掩码\n    bDetect      : BOOL;",
    demo_call="IF bDetect THEN\n    uliDelta := UInt64Xor(uliPrev, uliCurr);   // 1 表示该 bit 翻转过\n    bDetect := FALSE;\nEND_IF;",
)

_add("ULARGE_INTEGER",
    subdir="uint64", section="4.9.29", ret=ULI,
    inputs=[("dwHighPart","DWORD","-","上位 32 位"),
            ("dwLowPart","DWORD","-","下位 32 位")],
    in_out=[],
    purpose="构造一个 `T_ULARGE_INTEGER` 字面值：传入高 32 位与低 32 位 DWORD，返回拼装后的结构体。是构造 64 位无符号常量的标准入口。",
    behavior="函数把 dwHighPart 写入结构体的高字段、dwLowPart 写入低字段，并返回结构体。**这不是位移、不是相加**；构造的值在数值上等于 `dwHighPart * 2³² + dwLowPart`。最大值 `ULARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF)` = 2⁶⁴−1。常用于在 IEC ST 里写 64 位字面常量（IEC 没有 64 位无符号字面）。",
    ret_doc="`T_ULARGE_INTEGER` —— 由两个 DWORD 拼装而成的 64 位无符号整数。",
    pitfalls=[
        "**参数顺序是 high, low**（不是 low, high）—— 写反会得到大小颠倒的数",
        "想从纯十进制字符串构造请用 `STRING_TO_UINT64`",
        "想从原生 LWORD 构造请用 `LWORD_TO_ULARGE`",
    ],
    scenario="在 PLC 启动初始化时定义 64 位常量上限阈值 = 1E12。",
    value="替代手写结构体字段逐字段赋值；一行调用语义清晰。",
    demo_vars="uliThreshold : T_ULARGE_INTEGER;       // 1E12 字面常量\n    bInit        : BOOL := TRUE;",
    demo_call="IF bInit THEN\n    // 1E12 = 0xE8D4A51000 = high 0x00 + low 0xE8D4A51000？\n    // 实际 1E12 = 16#E8D4A51000 → high = 16#E8, low = 16#D4A51000\n    uliThreshold := ULARGE_INTEGER(16#E8, 16#D4A51000);\n    bInit := FALSE;\nEND_IF;",
)

_add("ULARGE_TO_ULINT",
    subdir="uint64", section="4.9.30", ret="ULINT",
    inputs=[("in",ULI,"-","待转换的 legacy 64 位无符号结构体")],
    in_out=[],
    purpose="把 TwinCAT 2 旧式 `T_ULARGE_INTEGER`（结构体）转换为 TwinCAT 3 原生 `ULINT`（64 位无符号整数）。原生类型支持 IEC `+ - * / mod` 直接运算，比结构体更便利。",
    behavior="函数把结构体的 dwHighPart 左移 32 位 OR dwLowPart 拼成 64 位 ULINT。等价于 `LWORD(in.dwHighPart) * 16#100000000 + LWORD(in.dwLowPart)`。无溢出风险（值域完全一致）。返回 ULINT 后可直接做算术。",
    ret_doc="`ULINT` —— 与 `in` 数值完全相等的原生 64 位整数。",
    pitfalls=[
        "**类型边界**：从结构体过到原生类型，相当于换了一种表示，原值不变",
        "ULINT 可直接用 `+ - * /`，远比结构体好用",
        "若结果还要回到 legacy 域请用 `LWORD_TO_ULARGE`（先经 `ULINT_TO_LWORD`）",
    ],
    scenario="ADS Raw 报文里读到一个 T_ULARGE_INTEGER 字段，业务逻辑全用 ULINT 算术，需要一步转换。",
    value="替代手写位移 + 加法；一行调用。",
    demo_vars="uliFromAds   : T_ULARGE_INTEGER;       // ADS 报文里读到的字段\n    ulNative     : ULINT;                  // 业务侧原生 64 位\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    ulNative := ULARGE_TO_ULINT(uliFromAds);   // 转换后即可参与 IEC 算术\n    bConvert := FALSE;\nEND_IF;",
)

_add("ULARGE_TO_LWORD",
    subdir="uint64", section="4.9.31", ret="LWORD",
    inputs=[("in",ULI,"-","待转换的 legacy 64 位无符号结构体")],
    in_out=[],
    purpose="把 TwinCAT 2 旧式 `T_ULARGE_INTEGER` 转换为 TwinCAT 3 原生 `LWORD`（64 位位串）。区别于 `ULARGE_TO_ULINT`：`LWORD` 偏向位运算语义，`ULINT` 偏向算术。",
    behavior="按位拼接 dwHighPart 与 dwLowPart 得到 LWORD。无溢出。`LWORD` 在 TwinCAT 3 里可直接 `AND OR XOR SHL SHR` 而无须用本库的 `UInt64And` 等结构体函数。",
    ret_doc="`LWORD` —— 与 `in` 位级完全相等的 64 位位串。",
    pitfalls=[
        "区分：要做算术请用 `ULARGE_TO_ULINT`，要做位运算请用本函数",
        "**LWORD 和 ULINT 在 TwinCAT 3 是不同 IEC 类型**，混用需 `LWORD_TO_ULINT` 之类显式转",
        "想从 LWORD 回到 legacy 用 `LWORD_TO_ULARGE`",
    ],
    scenario="legacy 报文里读到的 64 位状态位转 LWORD 后直接用 IEC 原生 `AND` 屏蔽。",
    value="替代结构体位运算；之后可用原生 `AND/OR/SHR`，代码可读性更高。",
    demo_vars="uliStatus    : T_ULARGE_INTEGER;       // legacy 状态结构体\n    lwStatusBits : LWORD;                  // 转换后的位串\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    lwStatusBits := ULARGE_TO_LWORD(uliStatus);\n    bConvert := FALSE;\nEND_IF;",
)


# ===== 64 bit functions (signed) — 15 项 =====

_add("INT64_TO_LREAL",
    subdir="int64_signed", section="4.8.1", ret="LREAL",
    inputs=[("in",LI,"-","待转换的 legacy 有符号 64 位整数")],
    in_out=[],
    purpose="把 TwinCAT 2 旧式 `T_LARGE_INTEGER`（有符号 64 位结构体）转换为 LREAL 浮点。供 HMI 显示、报表、与浮点算法接口。",
    behavior="按结构体语义解读为有符号 64 位（最高位为符号位），再赋给 LREAL。LREAL 尾数 52 位，绝对值大于 2⁵³ 时丢精度。不会异常、不会 NaN。负数会被正确还原（取决于结构体字段的符号约定，PDF 视作两个 DWORD 拼接的二进制补码）。",
    ret_doc="`LREAL` —— 数值上等于 `in`；大于 2⁵³ 时是最近的浮点近似。",
    pitfalls=[
        "**大于 2⁵³ 丢精度**（≈ 9E15）",
        "用于显示无影响；用于算术建议保持整数域",
        "T_LARGE_INTEGER 的字段虽是 DWORD（无符号），但拼起来按二进制补码解读为有符号",
    ],
    scenario="把 64 位有符号扭矩积分（可正可负）转 LREAL 在 HMI 显示。",
    value="替代手写有符号双倍长转浮点；一行调用。",
    demo_vars="liTorqueInt  : T_LARGE_INTEGER;        // 有符号 64 位扭矩积分\n    lrTorqueDisp : LREAL;                  // HMI 显示\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    lrTorqueDisp := INT64_TO_LREAL(liTorqueInt);\n    bConvert := FALSE;\nEND_IF;",
)

_add("Int64Add64",
    subdir="int64_signed", section="4.8.2", ret=LI,
    inputs=[("i64a",LI,"-","加数 A"),
            ("i64b",LI,"-","加数 B")],
    in_out=[],
    purpose="两个有符号 64 位整数（`T_LARGE_INTEGER`）相加，**不检测溢出**。要溢出检测请用 `Int64Add64Ex`。",
    behavior="按二进制补码算术相加；结果落在 [−2⁶³, 2⁶³−1]，溢出时静默 wrap-around（与无符号语义一致，符号位翻转产生异号大数）。",
    ret_doc="`T_LARGE_INTEGER` —— 和，模 2⁶⁴。",
    pitfalls=[
        "**静默 wrap-around 改变符号** —— 正数相加溢出可能变负数，算金额慎用",
        "需检测请改 Ex 版",
        "结构体比较用 `Int64Cmp64`，不要 `=`",
    ],
    scenario="累计差值（可正可负）求合，确认不会超 2⁶³ 后用本函数。",
    value="替代手写有符号双倍长加；一行调用。",
    demo_vars="liAccum      : T_LARGE_INTEGER;        // 累计差值\n    liDelta      : T_LARGE_INTEGER;        // 本次差值\n    bAdd         : BOOL;",
    demo_call="IF bAdd THEN\n    liAccum := Int64Add64(liAccum, liDelta);\n    bAdd := FALSE;\nEND_IF;",
)

_add("Int64Add64Ex",
    subdir="int64_signed", section="4.8.3", ret=LI,
    inputs=[("augend",LI,"-","被加数"),
            ("addend",LI,"-","加数")],
    in_out=[("bOV","BOOL","-","算术溢出标志：TRUE = 溢出（每周期需先清零）")],
    purpose="带溢出检测的有符号 64 位加法。`bOV` 在和超出 [−2⁶³, 2⁶³−1] 时置 TRUE。",
    behavior="检测有符号溢出（与无符号不同：两正相加变负、或两负相加变正都算溢出）。返回值仍是 wrap-around 的低 64 位。`bOV` 是 VAR_IN_OUT，每周期开始处清零。",
    ret_doc="`T_LARGE_INTEGER` —— 低 64 位和；`bOV` 反映有符号溢出。",
    pitfalls=[
        "**有符号溢出**：两正变负、两负变正",
        "`bOV` 每周期清零",
        "饱和需手写：`IF bOV THEN result := <正/负 MAX>; END_IF;`",
    ],
    scenario="工业计量场景里有符号差值累加，溢出代表传感器故障要报警。",
    value="替代手写符号位检测；一次调用同时拿和与溢出位。",
    demo_vars="liAccum      : T_LARGE_INTEGER;\n    liDelta      : T_LARGE_INTEGER;\n    bOverflow    : BOOL;\n    bAdd         : BOOL;",
    demo_call="bOverflow := FALSE;                                    // 每周期先清\nIF bAdd THEN\n    liAccum := Int64Add64Ex(liAccum, liDelta, bOverflow);\n    IF bOverflow THEN\n        ;   // 业务层报警与饱和\n    END_IF;\n    bAdd := FALSE;\nEND_IF;",
)

_add("Int64Cmp64",
    subdir="int64_signed", section="4.8.4", ret="DINT",
    inputs=[("i64a",LI,"-","左操作数；返回 -1 表示 i64a 小于 i64b"),
            ("i64b",LI,"-","右操作数")],
    in_out=[],
    purpose="比较两个有符号 64 位整数，返回 -1 / 0 / 1（小于 / 等于 / 大于）。**有符号语义**：负数 < 正数。",
    behavior="按二进制补码有符号比较：`Int64Cmp64(ULARGE_INTEGER(16#80000000, 0), ULARGE_INTEGER(0, 0)) < 0`（最高位 1 是负数）。区别于 `UInt64Cmp64`：同样的位模式，符号语义不同结果完全相反。",
    ret_doc="`DINT` —— -1 / 0 / 1。",
    pitfalls=[
        "**有符号 vs 无符号语义** —— 同样字节模式比较结果可能相反，混库时要看清",
        "用 `Int64Cmp64(a, b) = 0` 判相等，不要直接 `a = b`",
        "排序时返回值可直接喂给 sort 回调",
    ],
    scenario="对一组有符号扭矩误差排序。",
    value="替代手写有符号比较；一行 DINT 比较一目了然。",
    demo_vars="liA          : T_LARGE_INTEGER;\n    liB          : T_LARGE_INTEGER;\n    diResult     : DINT;\n    bCompare     : BOOL;",
    demo_call="IF bCompare THEN\n    diResult := Int64Cmp64(liA, liB);\n    bCompare := FALSE;\nEND_IF;",
)

_add("Int64Div64Ex",
    subdir="int64_signed", section="4.8.5", ret=LI,
    inputs=[("dividend",LI,"-","被除数"),
            ("divisor",LI,"-","除数")],
    in_out=[("remainder",LI,"-","输出余数；调用方需提供左值变量")],
    purpose="有符号 64 位除法，同时返回商与余数。**注意**：有符号除法的舍入与余数符号与具体实现相关。",
    behavior="商按二进制补码有符号除法（向零截断，类似 C99 之后的语义）；余数符号与被除数相同（PDF 未明确，但工程实践如此 ⚠️）。`divisor = 0` PDF 未定义 ⚠️。`-2⁶³ / -1` 的边界场景在二进制补码里溢出（2⁶³ 不可表示），PDF 未定义 ⚠️。",
    ret_doc="`T_LARGE_INTEGER` —— 商；`remainder` —— 余数。",
    pitfalls=[
        "**除以 0 PDF 未定义** ⚠️",
        "**−2⁶³ ÷ −1 PDF 未定义** ⚠️（真实商 2⁶³ 不可表示）",
        "余数符号工程实践与被除数同号，但 PDF 未明示 ⚠️",
        "余数 VAR_IN_OUT，必须传左值",
    ],
    scenario="有符号 64 位测量值除以单位换算因子，同时记录余数做下次周期补偿。",
    value="替代手写有符号除法 + 余数符号处理；一次调用搞定。",
    demo_vars="liDividend   : T_LARGE_INTEGER;\n    liDivisor    : T_LARGE_INTEGER;\n    liQuotient   : T_LARGE_INTEGER;\n    liRemainder  : T_LARGE_INTEGER;\n    bDivide      : BOOL;",
    demo_call="IF bDivide AND NOT Int64IsZero(liDivisor) THEN\n    // 除 0 与 −2⁶³÷−1 边界 PDF 未定义 → 前置校验\n    liQuotient := Int64Div64Ex(liDividend, liDivisor, liRemainder);\n    bDivide := FALSE;\nEND_IF;",
)

_add("Int64IsZero",
    subdir="int64_signed", section="4.8.6", ret="BOOL",
    inputs=[("i64",LI,"-","待判定的有符号 64 位整数")],
    in_out=[],
    purpose="判断 `T_LARGE_INTEGER` 是否为 0。",
    behavior="检查 dwHighPart 与 dwLowPart 是否同时为 0。无副作用、单周期。注意 PDF 与代码均把函数名首字母写作大写 I，但返回值表格里函数名是 `Int64isZero`（小写 i）— 这是 PDF 排版不一致，IEC 标识符大小写无关，可两种写法 ⚠️。",
    ret_doc="`BOOL` —— TRUE = 0。",
    pitfalls=[
        "不要写 `liX = 0`（类型不匹配）；用本函数",
        "PDF 内函数名大小写不一致是排版问题，运行时不区分",
    ],
    scenario="除法 / 模运算前的除数校验。",
    value="替代结构体 `=` 比较。",
    demo_vars="liDivisor    : T_LARGE_INTEGER;\n    bIsZero      : BOOL;\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    bIsZero := Int64IsZero(liDivisor);\n    bCheck := FALSE;\nEND_IF;",
)

_add("Int64Negate",
    subdir="int64_signed", section="4.8.7", ret=LI,
    inputs=[("i64",LI,"-","待取负的有符号 64 位整数")],
    in_out=[],
    purpose="对有符号 64 位整数取负（求相反数）。",
    behavior="按二进制补码取负：`-x = NOT(x) + 1`。**边界**：`-(-2⁶³)` 数学上等于 2⁶³，但 2⁶³ 不可由 `T_LARGE_INTEGER` 表达（最大正数是 2⁶³−1），PDF 未定义 ⚠️（实际多数实现仍返回 −2⁶³，因为 NOT+1 周期性回绕）。其余值无风险。",
    ret_doc="`T_LARGE_INTEGER` —— −`i64`。",
    pitfalls=[
        "**−INT64_MIN PDF 未定义** ⚠️（数学不可表达）",
        "负负得正、零取负仍为零",
        "无溢出标志输出，调用前要确认输入不是 INT64_MIN",
    ],
    scenario="把累加器一次性\'反向\'应用到补偿量上：`error_sum := Int64Negate(error_sum)`。",
    value="替代手写 NOT + Add64 两步。",
    demo_vars="liValue      : T_LARGE_INTEGER;\n    liNegated    : T_LARGE_INTEGER;\n    bNegate      : BOOL;",
    demo_call="IF bNegate THEN\n    // 应保证 liValue <> INT64_MIN，否则 PDF 未定义\n    liNegated := Int64Negate(liValue);\n    bNegate := FALSE;\nEND_IF;",
)

_add("Int64Not",
    subdir="int64_signed", section="4.8.8", ret=LI,
    inputs=[("i64",LI,"-","操作数")],
    in_out=[],
    purpose="对 `T_LARGE_INTEGER` 做按位取反。注意'按位 NOT'与'算术取负 Negate'不同：NOT 后等于 −x − 1（二进制补码性质）。",
    behavior="对 dwHighPart、dwLowPart 分别取反。结果用作位掩码或按位逻辑；不要当算术 −x 用（差 1）。",
    ret_doc="`T_LARGE_INTEGER` —— 按位取反。",
    pitfalls=[
        "**Not ≠ Negate**：Int64Not(x) = −x − 1（二进制补码），不是 −x",
        "用作位掩码安全；用作算术请用 `Int64Negate`",
    ],
    scenario="构造\'除指定位以外全 1\'的掩码。",
    value="替代两次 DWORD NOT。",
    demo_vars="liMask       : T_LARGE_INTEGER;\n    liInverted   : T_LARGE_INTEGER;\n    bInvert      : BOOL;",
    demo_call="IF bInvert THEN\n    liInverted := Int64Not(liMask);\n    bInvert := FALSE;\nEND_IF;",
)

_add("Int64Sub64",
    subdir="int64_signed", section="4.8.9", ret=LI,
    inputs=[("i64a",LI,"-","被减数"),
            ("i64b",LI,"-","减数")],
    in_out=[],
    purpose="两个有符号 64 位整数相减，**不检测溢出**。",
    behavior="按二进制补码相减；溢出（两正减两负、或两负减两正越界）时静默 wrap-around，符号位翻转。Tc2_Utilities 没有 `Int64Sub64Ex`，需要溢出检测得自己组合：`Add64Ex(a, Negate(b))` 但要小心 `Negate(INT64_MIN)`。",
    ret_doc="`T_LARGE_INTEGER` —— 差。",
    pitfalls=[
        "**静默有符号溢出**",
        "没有 Ex 版本检测溢出 —— 工程上需要自己包",
        "想算两个时间戳差值用 ULARGE 系列比 LARGE 顺手（时间戳通常非负）",
    ],
    scenario="算两个有符号扭矩积分的差值。",
    value="替代手写有符号双倍长减法 + 借位。",
    demo_vars="liA          : T_LARGE_INTEGER;\n    liB          : T_LARGE_INTEGER;\n    liDiff       : T_LARGE_INTEGER;\n    bSubtract    : BOOL;",
    demo_call="IF bSubtract THEN\n    liDiff := Int64Sub64(liA, liB);\n    bSubtract := FALSE;\nEND_IF;",
)

_add("LARGE_INTEGER",
    subdir="int64_signed", section="4.8.10", ret=LI,
    inputs=[("dwHighPart","DWORD","-","上位 32 位（含符号位）"),
            ("dwLowPart","DWORD","-","下位 32 位")],
    in_out=[],
    purpose="构造一个 `T_LARGE_INTEGER`（有符号 64 位）字面值。语义同 `ULARGE_INTEGER`，差别只在解读：dwHighPart 的最高位被视为符号位（二进制补码）。",
    behavior="字段不变拼装：`dwHighPart * 2³² + dwLowPart`，按二进制补码解读为有符号整数。`LARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF)` = −1；`LARGE_INTEGER(16#80000000, 0)` = INT64_MIN。",
    ret_doc="`T_LARGE_INTEGER` —— 有符号 64 位字面常量。",
    pitfalls=[
        "**参数顺序 high, low**",
        "高位最高 bit 是符号位：`LARGE_INTEGER(16#80000000, 0)` 是最小负数",
        "写 −1：`LARGE_INTEGER(16#FFFFFFFF, 16#FFFFFFFF)`",
    ],
    scenario="初始化\'未设定\'哨兵值 = INT64_MIN。",
    value="替代字段逐字段赋值。",
    demo_vars="liSentinel   : T_LARGE_INTEGER;        // 未设定哨兵 = INT64_MIN\n    bInit        : BOOL := TRUE;",
    demo_call="IF bInit THEN\n    liSentinel := LARGE_INTEGER(16#80000000, 16#00000000);   // INT64_MIN\n    bInit := FALSE;\nEND_IF;",
)

_add("LARGE_TO_LINT",
    subdir="int64_signed", section="4.8.11", ret="LINT",
    inputs=[("in",LI,"-","待转换的 legacy 有符号 64 位结构体")],
    in_out=[],
    purpose="把 TwinCAT 2 旧式 `T_LARGE_INTEGER` 转换为 TwinCAT 3 原生 `LINT`（64 位有符号整数）。原生类型可直接用 IEC `+ − * / mod` 算术，比结构体方便。",
    behavior="按位拼接后按二进制补码解读为有符号 LINT。值域完全一致，无溢出风险。",
    ret_doc="`LINT` —— 数值等于 `in`。",
    pitfalls=[
        "ULARGE_TO_LARGE / LARGE_TO_LINT 是表示形式转换，数值不变",
        "想回到 legacy 用 `LINT_TO_LARGE`",
    ],
    scenario="ADS Raw 报文 T_LARGE_INTEGER 字段读出后转 LINT 做业务计算。",
    value="替代位移 + 强转。",
    demo_vars="liFromAds    : T_LARGE_INTEGER;        // ADS 读回\n    liNative     : LINT;                   // 业务侧原生\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    liNative := LARGE_TO_LINT(liFromAds);\n    bConvert := FALSE;\nEND_IF;",
)

_add("LARGE_TO_ULARGE",
    subdir="int64_signed", section="4.8.12", ret=ULI,
    inputs=[("in",LI,"-","待转换的有符号结构体")],
    in_out=[],
    purpose="把 `T_LARGE_INTEGER` 重新解读为 `T_ULARGE_INTEGER`：位模式不变，仅改变符号约定。",
    behavior="字段不变直接复制到无符号结构体。`-1` 变成 `2⁶⁴−1`，负数变成'对应位模式的大正数'。常用于把有符号计数器交给只接受无符号的 API。",
    ret_doc="`T_ULARGE_INTEGER` —— 与 `in` 位模式相同，符号语义改变。",
    pitfalls=[
        "**数值含义会变**：−1（有符号）变成 MAX64（无符号）",
        "工程上仅用于'借位作 bag of bits'的场景",
        "想正确做无符号转换（去除负数）要先 `Int64Negate` 或 `MAX(0, x)`",
    ],
    scenario="把有符号编码器累计转角（可负）按位模式塞进只接受无符号的哈希函数。",
    value="替代手动结构体字段拷贝。",
    demo_vars="liSigned     : T_LARGE_INTEGER;\n    uliUnsigned  : T_ULARGE_INTEGER;\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    uliUnsigned := LARGE_TO_ULARGE(liSigned);   // 位模式不变\n    bConvert := FALSE;\nEND_IF;",
)

_add("LINT_TO_LARGE",
    subdir="int64_signed", section="4.8.13", ret=LI,
    inputs=[("in","LINT","-","待转换的 TC3 原生有符号 64 位整数")],
    in_out=[],
    purpose="把 TC3 原生 `LINT` 转回 legacy 结构体 `T_LARGE_INTEGER`。",
    behavior="按位拆分高 32 / 低 32 位写入结构体字段。数值不变。",
    ret_doc="`T_LARGE_INTEGER` —— 与 `in` 数值相等。",
    pitfalls=[
        "纯表示形式转换，无副作用",
        "要交给只接受 legacy 的旧库函数时常用",
    ],
    scenario="本地用 LINT 做算术，调用一个只接 T_LARGE_INTEGER 的旧 FB 前转一下。",
    value="替代手写 SHR/AND/拼装。",
    demo_vars="liNative     : LINT := -123456789;\n    liLegacy     : T_LARGE_INTEGER;\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    liLegacy := LINT_TO_LARGE(liNative);\n    bConvert := FALSE;\nEND_IF;",
)

_add("LREAL_TO_INT64",
    subdir="int64_signed", section="4.8.14", ret=LI,
    inputs=[("in","LREAL","-","待转换的浮点数")],
    in_out=[],
    purpose="把 LREAL 浮点数转换为 legacy 有符号 64 位 `T_LARGE_INTEGER`。",
    behavior="按四舍五入或截断（PDF 未明确 ⚠️）转换。LREAL 在 ±2⁵³ 之外不精确，超出 ±2⁶³ 边界 PDF 未定义。NaN、Inf PDF 未定义 ⚠️。",
    ret_doc="`T_LARGE_INTEGER` —— 转换后的有符号整数。",
    pitfalls=[
        "**舍入模式 PDF 未明确** ⚠️",
        "**NaN / Inf PDF 未定义** ⚠️ —— 调用前用 `LrealIsNaN` / `LrealIsFinite` 校验",
        "**±2⁶³ 之外 PDF 未定义** ⚠️",
        "大于 2⁵³ 时 LREAL 已经丢精度",
    ],
    scenario="把 PID 输出的浮点速度命令转有符号 64 位的累计步数。",
    value="替代手写浮点→双倍长整数；一行调用。",
    demo_vars="lrCmd        : LREAL := -1.5E9;\n    liSteps      : T_LARGE_INTEGER;\n    bConvert     : BOOL;",
    demo_call="IF bConvert AND LrealIsFinite(lrCmd) THEN\n    // 排除 NaN / Inf —— PDF 未定义这些情况\n    liSteps := LREAL_TO_INT64(lrCmd);\n    bConvert := FALSE;\nEND_IF;",
)

_add("ULARGE_TO_LARGE",
    subdir="int64_signed", section="4.8.15", ret=LI,
    inputs=[("in",ULI,"-","待转换的无符号结构体")],
    in_out=[],
    purpose="把 `T_ULARGE_INTEGER` 重新解读为 `T_LARGE_INTEGER`：位模式不变，符号约定改变。",
    behavior="字段直接复制到有符号结构体。`MAX64`（无符号）变成 `−1`（有符号），高位置 1 的无符号大数变成有符号负数。",
    ret_doc="`T_LARGE_INTEGER` —— 与 `in` 位模式相同。",
    pitfalls=[
        "**数值含义会变** —— 大无符号数变小负数",
        "若 `in` ≤ INT64_MAX（高位 0）则数值不变",
        "需要真实截断到有符号：先 `UInt64Min(in, ULARGE_INTEGER(16#7FFFFFFF, 16#FFFFFFFF))`",
    ],
    scenario="无符号读回的位串希望按有符号显示（比如负温度的差值表示）。",
    value="替代字段复制。",
    demo_vars="uliRaw       : T_ULARGE_INTEGER;\n    liSigned     : T_LARGE_INTEGER;\n    bConvert     : BOOL;",
    demo_call="IF bConvert THEN\n    liSigned := ULARGE_TO_LARGE(uliRaw);\n    bConvert := FALSE;\nEND_IF;",
)


# ===== 16 bit fixed point number functions (signed) — 9 项 =====

_add("FIX16_TO_LREAL",
    subdir="fix16", section="4.7.1", ret="LREAL",
    inputs=[("in","T_FIX16","-","待转换的定点数")],
    in_out=[],
    purpose="把 `T_FIX16`（有符号 16 位定点数 / Q-format 定点 INT）转换为 LREAL 浮点。`T_FIX16` 实际是 `INT`：高几位整数 + 低几位小数；具体小数位数由配套的 `n` 参数（构造时）决定。",
    behavior="`T_FIX16` 是 16 位整数，但解读时需要配套的小数位数 `n`。**本函数本身不需要 `n`，因为 PDF 标记 T_FIX16 自带 n 信息**（实际上是 `INT` 加约定）。返回 LREAL = `INT / 2ⁿ`。无溢出（INT 16 位最多 ±32767，LREAL 远大于此）。无 NaN / Inf 风险。",
    ret_doc="`LREAL` —— 解码后的浮点值。",
    pitfalls=[
        "`T_FIX16` 实际是 `INT`，配套的小数位数 `n` 在构造（`LREAL_TO_FIX16(v, n)`）时确定，无法从 INT 单独还原 —— 调用方必须自己跟踪 n",
        "PDF 示例里 `result := FIX16_TO_LREAL(FIX16Add(a, b))` 假设 a, b 已含相同 n 信息",
        "如果原始 n 与现在解读用的 n 不一致，结果会差 2 的整次幂",
    ],
    scenario="把 0.6 的定点数（Q8）转回 LREAL 显示，结果为 0.6015625（误差来自 0.6 不能精确表达）。",
    value="替代手写 `LREAL(in) / 256.0`；可读性更高，与 `LREAL_TO_FIX16` 对称使用。",
    demo_vars="fp8Setpoint  : T_FIX16 := 154;        // 0.6 在 Q8 编码 ≈ 154/256 = 0.6015625\n    lrDisp       : LREAL;\n    bDecode      : BOOL;",
    demo_call="IF bDecode THEN\n    // 注：解码方必须知道 n（这里 n=8）；本函数不接受 n 参数\n    lrDisp := FIX16_TO_LREAL(fp8Setpoint);\n    bDecode := FALSE;\nEND_IF;",
)

_add("FIX16_TO_WORD",
    subdir="fix16", section="4.7.2", ret="WORD",
    inputs=[("in","T_FIX16","-","待转换的定点数（视为 INT 位模式）")],
    in_out=[],
    purpose="把 `T_FIX16` 按位模式直接复制为 `WORD`（用于报文打包、SDO 写入等需要'原始 16 位字'的场合）。",
    behavior="位模式不变（INT 与 WORD 在 IEC 中位级等价，仅符号语义不同）。负的 T_FIX16 转为 WORD 后得到一个高位置 1 的大无符号数。常配合 `WORD_TO_FIX16` 反向使用，用于 SDO 通讯里把定点编码值放进 WORD 容器。",
    ret_doc="`WORD` —— 16 位位串，与 `in` 位模式相同。",
    pitfalls=[
        "**位模式不变，数值含义变** —— 负定点变大无符号数",
        "PDF 示例 `LREAL_TO_FIX16(12.5, 8)` 得到的 INT 经 FIX16_TO_WORD 后是 `2#0000110010000000` (= 0x0C80 = 3200)，对应 12.5×256",
    ],
    scenario="把 PID 比例系数（定点）写入 EtherCAT SDO 16 位字段。",
    value="替代 `INT_TO_WORD` 显式转换；语义上更明确（来源是定点而非普通整数）。",
    demo_vars="fp8Kp        : T_FIX16;\n    wSdoData     : WORD;                  // 写入 SDO 的 16 位字\n    bPack        : BOOL;",
    demo_call="// 假设上游已用 LREAL_TO_FIX16(0.5, 8) 得到 fp8Kp\nfp8Kp := LREAL_TO_FIX16(0.5, 8);\nIF bPack THEN\n    wSdoData := FIX16_TO_WORD(fp8Kp);   // 写到 SDO\n    bPack := FALSE;\nEND_IF;",
)

_add("FIX16Add",
    subdir="fix16", section="4.7.3", ret="T_FIX16",
    inputs=[("augend","T_FIX16","-","第一加数"),
            ("addend","T_FIX16","-","第二加数")],
    in_out=[],
    purpose="两个有符号 16 位定点数相加。**两侧的小数位数（resolution / n）若不同**，函数会先把高分辨率一侧截断到低分辨率，再相加。",
    behavior="算法：把分辨率更高的一侧做右移截断（丢弃多余小数位），使二者分辨率对齐，再做 INT 相加。和仍是 16 位有符号 INT，溢出按 IEC INT 加法 wrap-around（PDF 未明示行为 ⚠️，但 INT 加法是 IEC 规定的）。**调用方负责跟踪 n**：本函数不返回结果的 n，调用方必须知道结果的分辨率等于两输入中较低的那个。PDF 示例 `LREAL_TO_FIX16(0.5, 8) + LREAL_TO_FIX16(-0.25, 8) → 0.25`。",
    ret_doc="`T_FIX16` —— 和，分辨率 = `min(n_augend, n_addend)`。",
    pitfalls=[
        "**高分辨率一侧的小数位被静默截断** —— 不四舍五入，直接丢",
        "**和可能溢出 16 位 INT** —— PDF 未明示溢出行为 ⚠️",
        "调用方需自己跟踪结果分辨率（不在签名里）",
        "想做精确累加请用 LREAL",
    ],
    scenario="电机 PID 算法里两个相同分辨率的误差项做累加。",
    value="替代手写'分辨率对齐 + INT 加法 + 越界检查'；本函数封装了对齐步骤。",
    demo_vars="fp8A         : T_FIX16;\n    fp8B         : T_FIX16;\n    fp8Sum       : T_FIX16;\n    lrResult     : LREAL;\n    bAdd         : BOOL;",
    demo_call="// 与 PDF 示例对齐：0.5 + (-0.25) = 0.25（同为 Q8 编码）\nfp8A := LREAL_TO_FIX16(0.5,  8);\nfp8B := LREAL_TO_FIX16(-0.25, 8);\nIF bAdd THEN\n    fp8Sum   := FIX16Add(fp8A, fp8B);\n    lrResult := FIX16_TO_LREAL(fp8Sum);   // 应为 0.25\n    bAdd := FALSE;\nEND_IF;",
)

_add("FIX16Align",
    subdir="fix16", section="4.7.4", ret="T_FIX16",
    inputs=[("in","T_FIX16","-","待改变分辨率的定点数"),
            ("n","BYTE(0..15)","-","目标小数位数，范围 0..15")],
    in_out=[],
    purpose="改变 `T_FIX16` 的小数位数（resolution）：把当前的 Q-format 重新对齐到新的 n。例如把 Q8 转 Q4 会丢失低 4 位精度。",
    behavior="函数对内部 INT 值做位移以适配新 n。若新 n 小于原 n，丢失低位（截断）；若大于原 n，左移补 0（精度名义提高但实际信息没增加）。`n` 必须在 0..15。PDF 示例：`LREAL_TO_FIX16(0.6, 8)` 得 154（≈ 0.6015625），`FIX16Align(154, 4)` 转 Q4 = 9（= 0.5625，丢精度）。",
    ret_doc="`T_FIX16` —— 新分辨率的定点数。",
    pitfalls=[
        "**调用方需跟踪原 n**：本函数无法从 INT 单独推断当前 n",
        "**n 必须在 0..15** —— PDF 限定",
        "降低 n 会丢精度（如示例 0.6015625 → 0.5625）",
    ],
    scenario="不同子模块要求不同分辨率，需要把上游 Q8 信号转 Q4 喂给下游。",
    value="替代手写 SHR/SHL；语义清晰、符合 PDF 命名。",
    demo_vars="fp8Source    : T_FIX16;       // Q8 来源\n    fp4Aligned   : T_FIX16;       // Q4 输出\n    lrCheck      : LREAL;\n    bAlign       : BOOL;",
    demo_call="fp8Source := LREAL_TO_FIX16(0.6, 8);   // Q8: ~0.6015625\nIF bAlign THEN\n    fp4Aligned := FIX16Align(fp8Source, 4);          // Q4: 0.5625\n    lrCheck    := FIX16_TO_LREAL(fp4Aligned);\n    bAlign := FALSE;\nEND_IF;",
)

_add("FIX16Div",
    subdir="fix16", section="4.7.5", ret="T_FIX16",
    inputs=[("dividend","T_FIX16","-","被除数"),
            ("divisor","T_FIX16","-","除数")],
    in_out=[],
    purpose="两个有符号 16 位定点数相除。分辨率不同时先对齐到低分辨率再除。",
    behavior="按 PDF：高分辨率一侧的小数位被截断，再做 INT 除法。`divisor = 0` PDF 未定义 ⚠️。商仍是 T_FIX16（16 位 INT），溢出未明示。PDF 示例 `−22.5 / 10.0` 都为 Q8 → 结果 −2.25。",
    ret_doc="`T_FIX16` —— 商，分辨率 = `min(n_dividend, n_divisor)`。",
    pitfalls=[
        "**除以 0 PDF 未定义** ⚠️",
        "高分辨率一侧小数位被截断（不四舍五入）",
        "商可能溢出 16 位 INT，PDF 未明示 ⚠️",
        "调用方需跟踪结果分辨率",
    ],
    scenario="把两个定点测量量做比值（如电压 / 电流 = 电阻）显示。",
    value="替代手写分辨率对齐 + INT 除法。",
    demo_vars="fp8A         : T_FIX16;\n    fp8B         : T_FIX16;\n    fp8Quot      : T_FIX16;\n    lrResult     : LREAL;\n    bDivide      : BOOL;",
    demo_call="fp8A := LREAL_TO_FIX16(-22.5, 8);\nfp8B := LREAL_TO_FIX16(10.0, 8);\nIF bDivide AND fp8B <> 0 THEN\n    fp8Quot  := FIX16Div(fp8A, fp8B);\n    lrResult := FIX16_TO_LREAL(fp8Quot);   // 应为 -2.25\n    bDivide := FALSE;\nEND_IF;",
)

_add("FIX16Mul",
    subdir="fix16", section="4.7.6", ret="T_FIX16",
    inputs=[("multiA","T_FIX16","-","第一乘数"),
            ("multiB","T_FIX16","-","第二乘数")],
    in_out=[],
    purpose="两个有符号 16 位定点数相乘。分辨率不同时先对齐到低分辨率再乘。",
    behavior="高分辨率一侧截断小数位，再做 INT 乘法。结果仍 16 位 INT，可能溢出（如 0.25 * 0.25 在 Q4 下结果 = 1 / 16，但 25 * 25 = 625 在 Q4 编码里要表示 1/16 实际为 1，超过 Q4 表示范围则截断 ⚠️）。PDF 示例 `0.25 * 10.0` 都 Q8 → 2.5。",
    ret_doc="`T_FIX16` —— 积，分辨率 = `min(n_A, n_B)`。",
    pitfalls=[
        "**积可能溢出 16 位 INT** —— 大数相乘前最好先做范围估计",
        "高分辨率一侧小数位截断",
        "调用方跟踪结果分辨率",
    ],
    scenario="把 PID 的比例系数（定点）× 误差（定点）= 输出（定点）。",
    value="替代手写对齐 + INT 乘法。",
    demo_vars="fp8A         : T_FIX16;\n    fp8B         : T_FIX16;\n    fp8Prod      : T_FIX16;\n    lrResult     : LREAL;\n    bMul         : BOOL;",
    demo_call="fp8A := LREAL_TO_FIX16(0.25, 8);\nfp8B := LREAL_TO_FIX16(10.0, 8);\nIF bMul THEN\n    fp8Prod  := FIX16Mul(fp8A, fp8B);\n    lrResult := FIX16_TO_LREAL(fp8Prod);   // 应为 2.5\n    bMul := FALSE;\nEND_IF;",
)

_add("FIX16Sub",
    subdir="fix16", section="4.7.7", ret="T_FIX16",
    inputs=[("minuend","T_FIX16","-","被减数"),
            ("subtrahend","T_FIX16","-","减数")],
    in_out=[],
    purpose="两个有符号 16 位定点数相减。分辨率不同时先对齐到低分辨率。",
    behavior="高分辨率一侧截断小数位，再做 INT 减法。差仍 16 位 INT，溢出未明示 ⚠️。PDF 示例 `0.5 − 0.75 = −0.25`（同 Q8）。",
    ret_doc="`T_FIX16` —— 差，分辨率 = `min(n_minuend, n_subtrahend)`。",
    pitfalls=[
        "**差可能溢出 16 位 INT** —— PDF 未明示行为 ⚠️",
        "高分辨率一侧截断",
        "调用方跟踪结果分辨率",
    ],
    scenario="读两个传感器之差用于偏差控制。",
    value="替代手写对齐 + INT 减法。",
    demo_vars="fp8A         : T_FIX16;\n    fp8B         : T_FIX16;\n    fp8Diff      : T_FIX16;\n    lrResult     : LREAL;\n    bSub         : BOOL;",
    demo_call="fp8A := LREAL_TO_FIX16(0.5,  8);\nfp8B := LREAL_TO_FIX16(0.75, 8);\nIF bSub THEN\n    fp8Diff  := FIX16Sub(fp8A, fp8B);\n    lrResult := FIX16_TO_LREAL(fp8Diff);   // 应为 -0.25\n    bSub := FALSE;\nEND_IF;",
)

_add("LREAL_TO_FIX16",
    subdir="fix16", section="4.7.8", ret="T_FIX16",
    inputs=[("in","LREAL","-","待转换的 LREAL 浮点数"),
            ("n","WORD(0..15)","15","目标小数位数（默认 15，最高精度）")],
    in_out=[],
    purpose="把 LREAL 浮点数转换为 `T_FIX16` 定点数，调用方指定小数位数 `n`。是定点编码的标准入口。",
    behavior="算法：`result := INT(in * 2ⁿ)`（PDF 文末提示\'可能产生舍入误差\'）。`n` 必须在 0..15；超出 PDF 未定义 ⚠️。`in * 2ⁿ` 若超出 −32768..32767 范围，结果按 INT 截断 ⚠️。PDF 示例：0.6 / 0.25 / 0.75 / 50000.5 在不同 n 下的输出，最大 q15 可能溢出（50000 不能用 Q15 表达）。",
    ret_doc="`T_FIX16` —— 定点编码值，分辨率由 `n` 决定。",
    pitfalls=[
        "**`|in * 2ⁿ|` 超过 32767 会溢出** —— PDF 未明示 ⚠️",
        "**舍入误差**：0.6 / 0.1 等无法精确二进制表达的常数会引入误差",
        "`n` 默认 15，最高精度但范围最小（±1.0）；`n = 0` 范围最大（±32767）但无小数",
        "工程上对每路信号固定 n，全局一致以避免运算时频繁 Align",
    ],
    scenario="HMI 输入 0.5 的比例系数转 Q8 定点供 PID 用。",
    value="替代手写 `INT(in * 256)`；附带范围提示和默认 n。",
    demo_vars="lrKp         : LREAL := 0.5;\n    fp8Kp        : T_FIX16;\n    bEncode      : BOOL;",
    demo_call="IF bEncode THEN\n    // 工程统一使用 Q8 → n = 8\n    fp8Kp := LREAL_TO_FIX16(lrKp, 8);\n    bEncode := FALSE;\nEND_IF;",
)

_add("WORD_TO_FIX16",
    subdir="fix16", section="4.7.9", ret="T_FIX16",
    inputs=[("in","WORD","-","16 位定点数的位模式"),
            ("n","WORD(0..15)","-","小数位数")],
    in_out=[],
    purpose="把 WORD 按位模式解读为 `T_FIX16`，调用方提供小数位数 `n`。常用于 SDO / 报文里读回的 WORD 重新解读为定点。",
    behavior="位模式直接转 INT；`n` 用于跟踪元数据（实际计算时配合 FIX16_TO_LREAL 才用到 n）。PDF 示例：`FIX16_TO_LREAL(WORD_TO_FIX16(2#0000110010000000, 8))` = 12.5。",
    ret_doc="`T_FIX16` —— 定点数，分辨率为 `n`。",
    pitfalls=[
        "**位模式不变**：WORD 与 INT 在 IEC 等价",
        "**`n` 必须与编码侧一致** —— 否则数值解读错",
        "工程上把 (WORD, n) 视为一个 pair，整段代码保持同 n",
    ],
    scenario="EtherCAT SDO 读回 16 位字，重新解读为 Q8 定点。",
    value="替代 `INT_TO_FIX16(WORD_TO_INT(...), n)` 两层转换。",
    demo_vars="wFromSdo     : WORD := 2#0000110010000000;   // PDF 示例值 = 12.5 in Q8\n    fp8Decoded   : T_FIX16;\n    lrCheck      : LREAL;\n    bDecode      : BOOL;",
    demo_call="IF bDecode THEN\n    fp8Decoded := WORD_TO_FIX16(wFromSdo, 8);\n    lrCheck    := FIX16_TO_LREAL(fp8Decoded);   // 应为 12.5\n    bDecode := FALSE;\nEND_IF;",
)


# ===== FLOAT functions — 4 项 =====

_add("LrealIsFinite",
    subdir="float", section="4.4.2", ret="BOOL",
    inputs=[("x","REFERENCE TO LREAL","-","待测试的浮点引用；本函数检查它是否为有限值（非 NaN / 非 ±Inf）")],
    in_out=[],
    purpose="判断一个 LREAL 是否是**有限**值，即既不是 NaN（Not a Number）也不是 ±Inf。返回 TRUE 表示输入是普通浮点数，可参与后续算术 / 比较 / 显示。",
    behavior="按 IEEE 754 双精度规范：指数全 1 且尾数非 0 即 NaN，指数全 1 且尾数为 0 即 ±Inf，二者均不算 Finite。输入用 `REFERENCE TO LREAL` 传址（无 8 字节拷贝开销）。无副作用、无错误码、单 PLC 周期完成。Tc2_Utilities 版本 ≥ 3.3.16.0、TwinCAT 编译器 ≥ 3.1.4020 才提供本函数。",
    ret_doc="`BOOL` —— TRUE = 有限值；FALSE = NaN 或 ±Inf。",
    pitfalls=[
        "**REFERENCE TO LREAL**：传址，参数侧必须是真实左值，不可传常量 / 表达式",
        "等价于'`NOT LrealIsNaN(x) AND NOT (x = INFINITY)`\'，但本函数是单次调用",
        "对一个 NaN 用 `IF x > 0` 这种比较恒为 FALSE（NaN 比较语义），所以'判 finite 后再比较'是稳健写法",
        "需要 TwinCAT ≥ 3.1.4020 + Tc2_Utilities ≥ 3.3.16.0",
    ],
    scenario="PID 输出做电机命令前必须先 finite 校验，否则下游 LREAL_TO_INT64 命中 PDF 未定义。",
    value="替代手写 IEEE 754 位检测；一次调用语义清晰。",
    demo_vars="lrPidOut     : LREAL;                  // PID 输出\n    bFinite      : BOOL;                   // 是否安全使用\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    // 必须用变量传址 —— REFERENCE TO 不接表达式\n    bFinite := LrealIsFinite(lrPidOut);\n    bCheck := FALSE;\nEND_IF;",
)

_add("LrealIsNaN",
    subdir="float", section="4.4.3", ret="BOOL",
    inputs=[("x","REFERENCE TO LREAL","-","待测试的浮点引用；本函数检查它是否为 NaN")],
    in_out=[],
    purpose="判断一个 LREAL 是否是 NaN（Not a Number，IEEE 754 非数）。返回 TRUE 表示是 NaN。",
    behavior="IEEE 754 双精度 NaN 的主要性质（PDF 详列）：(1) 所有以 NaN 为输入的算术运算结果仍是 NaN；(2) 关系运算符 = != > < >= <= 在任一操作数为 NaN 时**永远返回 FALSE**；(3) `NaN = NaN` 在 IEC 里恒 FALSE，所以表达式 `NOT(a = a)` 等价于 `isnan(a)`；(4) NaN 在级联运算中'自反'地传播下去，作为错误传播载体很有用。本函数等价于 `NOT(x = x)`，但更明确。无副作用、单周期。需要 TwinCAT ≥ 3.1.4020 + Tc2_Utilities ≥ 3.3.16.0。",
    ret_doc="`BOOL` —— TRUE = NaN。",
    pitfalls=[
        "**不要用 `x = NAN` 判 NaN** —— NaN 比较恒 FALSE，永远判不出",
        "用本函数或 `NOT(x = x)`",
        "NaN 在后续算术里'自反'传播：x + 1, x * 2 都仍是 NaN",
        "比较运算遇 NaN 恒 FALSE，所以 `IF x > 0` 在 NaN 时不会进 THEN 分支（但也不会进 ELSE 分支，得用 ELSIF）",
    ],
    scenario="积分器算出 0/0 后变 NaN，在喂下游前判 NaN 切回安全默认值。",
    value="替代手写 `NOT(x = x)`；语义清晰。",
    demo_vars="lrSensor     : LREAL;\n    bIsNaN       : BOOL;\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    bIsNaN := LrealIsNaN(lrSensor);\n    bCheck := FALSE;\nEND_IF;",
)

_add("RealIsFinite",
    subdir="float", section="4.4.4", ret="BOOL",
    inputs=[("x","REFERENCE TO REAL","-","待测试的浮点引用；本函数检查它是否为有限值")],
    in_out=[],
    purpose="判断一个 REAL（32 位单精度）是否是**有限**值（非 NaN、非 ±Inf）。LREAL 版本是 `LrealIsFinite`。",
    behavior="按 IEEE 754 单精度规范判断；接口与 `LrealIsFinite` 完全对称只是宽度不同。需要 TwinCAT ≥ 3.1.4024.32 + Tc2_Utilities ≥ 3.3.50.0。",
    ret_doc="`BOOL` —— TRUE = 有限。",
    pitfalls=[
        "**REFERENCE TO REAL**：传址要真实左值",
        "REAL 精度比 LREAL 低（尾数 23 位 vs 52 位）—— 边界值更容易超出表示范围导致 Inf",
        "需要 TwinCAT 3.1.4024.32 + Tc2_Utilities ≥ 3.3.50.0",
    ],
    scenario="32 位 ADC 采样转 REAL 后，过滤掉因传感器开路 / 短路造成的 ±Inf 异常值。",
    value="替代手写位检测；与 LrealIsFinite 对称。",
    demo_vars="rAdcSample   : REAL;\n    bFinite      : BOOL;\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    bFinite := RealIsFinite(rAdcSample);\n    bCheck := FALSE;\nEND_IF;",
)

_add("RealIsNaN",
    subdir="float", section="4.4.5", ret="BOOL",
    inputs=[("x","REFERENCE TO REAL","-","待测试的浮点引用；本函数检查它是否为 NaN")],
    in_out=[],
    purpose="判断一个 REAL 是否是 NaN（IEEE 754 单精度非数）。语义与 `LrealIsNaN` 对称，只是宽度不同。",
    behavior="IEEE 754 单精度 NaN 的核心性质：(1) NaN 参与算术得 NaN；(2) 关系运算遇 NaN 恒 FALSE；(3) `NaN = NaN` 为 FALSE，可用 `NOT(x = x)` 等价测试；(4) NaN 在级联中自反传播。需要 TwinCAT ≥ 3.1.4024.32 + Tc2_Utilities ≥ 3.3.50.0。",
    ret_doc="`BOOL` —— TRUE = NaN。",
    pitfalls=[
        "**不要用 `x = NAN`** —— 恒 FALSE",
        "用本函数或 `NOT(x = x)`",
        "REAL 的 NaN 与 LREAL 的 NaN 在表示上不同（24 位 vs 53 位尾数），但语义相同",
    ],
    scenario="温度传感器 32 位读回值经 1/0 计算被污染为 NaN，喂控制器前需判 NaN 后切默认值。",
    value="替代位检测；与 LrealIsNaN 对称。",
    demo_vars="rSensor      : REAL;\n    bIsNaN       : BOOL;\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    bIsNaN := RealIsNaN(rSensor);\n    bCheck := FALSE;\nEND_IF;",
)


# ===== LCOMPLEX functions — 2 项 =====

_add("LcomplexIsNaN",
    subdir="lcomplex", section="4.5.1", ret="BOOL",
    inputs=[("Z","REFERENCE TO LCOMPLEX","-","待测试的复数引用；本函数检查实部或虚部是否为 NaN")],
    in_out=[],
    purpose="判断一个 `LCOMPLEX`（实部 + 虚部均为 LREAL）是否含有 NaN。返回 TRUE 表示**实部或虚部至少一个是 NaN**。常用于矢量控制 d-q 变换、阻抗计算后做合法性校验。",
    behavior="函数对实部与虚部分别做 IEEE 754 NaN 测试（参考 `LrealIsNaN`），任一为 NaN 则返回 TRUE。无副作用、单周期。需要 TwinCAT ≥ 3.1.4020 + Tc2_Utilities ≥ 3.3.16.0。",
    ret_doc="`BOOL` —— TRUE = 实部或虚部为 NaN。",
    pitfalls=[
        "**REFERENCE TO LCOMPLEX**：传址要真实左值",
        "本函数把'任一为 NaN'视为 NaN，不区分实虚",
        "复数算术中除以 0（如 1/(0+0j)）会让结果有 NaN，要在传播到下游前拦截",
    ],
    scenario="矢量控制 d-q 反变换后，电流复数若含 NaN 必须切回上一周期值以保险。",
    value="替代手写 `LrealIsNaN(Z.re) OR LrealIsNaN(Z.im)`；一次调用语义清晰。",
    demo_vars="lcCurrent    : LCOMPLEX;       // d-q 反变换电流\n    bHasNaN      : BOOL;\n    bCheck       : BOOL;",
    demo_call="IF bCheck THEN\n    bHasNaN := LcomplexIsNaN(lcCurrent);\n    bCheck := FALSE;\nEND_IF;",
)

_add("LcomplexAbs",
    subdir="lcomplex", section="4.5.2", ret="LREAL",
    inputs=[("Z","LCOMPLEX","-","复数；返回它的模 √(re² + im²)")],
    in_out=[],
    purpose="返回 `LCOMPLEX` 的模（绝对值 / magnitude）= √(re² + im²)。常用于矢量幅度（电压幅值、电流幅值、阻抗模）显示与判定。",
    behavior="函数计算欧氏范数：`SQRT(Z.re² + Z.im²)`。底层实现一般用 `HYPOT(re, im)` 避免在 re² 或 im² 单独溢出/下溢时丢精度。NaN 输入返回 NaN；±Inf 输入返回 +Inf。需要 TwinCAT ≥ 3.1.4022 + Tc2_Utilities ≥ 3.3.21.0。",
    ret_doc="`LREAL` —— 模，非负；NaN 输入返回 NaN，±Inf 输入返回 +Inf。",
    pitfalls=[
        "**注意 `Z` 是按值传递**（不是 REFERENCE）—— 不同于 `LcomplexIsNaN`",
        "巨大幅值（接近 ±1E154）平方会溢出 LREAL；底层用 HYPOT 通常能避免",
        "需要 TwinCAT ≥ 3.1.4022 + Tc2_Utilities ≥ 3.3.21.0（注意比 IsNaN 高一个补丁）",
        "结果是 LREAL，下游若要整数请显式 LREAL_TO_LINT",
    ],
    scenario="变频器 d-q 电流幅值 = √(id² + iq²) 用于过电流保护比较。",
    value="替代手写 `SQRT(re*re + im*im)`；HYPOT 实现在极端值下更稳。",
    demo_vars="lcCurrent    : LCOMPLEX;\n    lrAbs        : LREAL;\n    bCompute     : BOOL;",
    demo_call="IF bCompute AND NOT LcomplexIsNaN(lcCurrent) THEN\n    // 先判 NaN 避免传播\n    lrAbs := LcomplexAbs(lcCurrent);\n    bCompute := FALSE;\nEND_IF;",
)


assert len(META) == 61, f"Expected 61 entries, got {len(META)}"
