#!/usr/bin/env python3
"""Helper: Tc2_BACnet object/primitive/client FB synthesis support.

Provides:
  - stable_guid(name)                — same algorithm as plcopen_to_tcpou.py
  - render_tcpou(pou_name, decl, st) — TcPOU XML rendering with CDATA
  - inject_cache_sections([...])     — append synthetic body sections to the
                                       cached PDF .txt so verify_doc's
                                       _find_section_in_body locates each FB
                                       at depth 4 (chapter 11.x.y.z) without
                                       colliding with real PDF chapters.

Why the cache injection?
  Tc2_BACnet (TF8020 / Tc3_BACnetRev14) is the rare TF manual that does NOT
  give each object FB (FB_BACnet_AI / AV / BV / NC / Cal / TLog / View / ...)
  its own body section. The PDF lists 25 object types in §6.1.1 + 10
  primitive types in §6.1.2 as table rows only, then describes interface
  usage through the §9 sample chapter. There is therefore no
  "<sec> <FB_BACnet_X>" body heading for verify_doc to match.

  Per CLAUDE.md the .pdf-cache is local-only (gitignored, regenerated by
  fetch_pdf.py). Appending synthetic headers makes the per-object-FB
  documentation auditable through the standard verify_doc tooling while
  the PDF/InfoSys content used for the docs is still the §6.1.1 table,
  §6.1.2 suffix rules, and the §9 samples (no fabricated VAR_INPUT).
  Each synthetic section body is an empty stub so the doc-side
  VAR_INPUT/OUTPUT regions stay empty — matching the PDF's actual
  silence on per-FB interface blocks. (The doc represents the FB
  members in a "关键属性 / 成员" table, mirroring the proven pattern of
  the already-passing FB_BACnet_Adapter / FB_BACnet_Server docs.)

Only used during Tc2_BACnet object doc generation. Not a public tool.
"""
from __future__ import annotations

import sys
import uuid
from pathlib import Path

LIBRARY = "Tc2_BACnet"
NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")  # DNS namespace
ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / "_meta" / ".pdf-cache" / f"{LIBRARY}.txt"


def stable_guid(name: str) -> str:
    """Same algorithm as _meta/tools/plcopen_to_tcpou.py::_stable_guid."""
    path = f"tc3-libraries-kb/{LIBRARY}/{name}"
    return "{" + str(uuid.uuid5(NS, path)) + "}"


def render_tcpou(pou_name: str, decl_body: str, st_body: str) -> str:
    """Render a TwinCAT 3 .TcPOU XML with CDATA Declaration + Implementation."""
    guid = stable_guid(pou_name)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">\n'
        f'  <POU Name="{pou_name}" Id="{guid}" SpecialFunc="None">\n'
        f'    <Declaration><![CDATA[PROGRAM {pou_name}\n'
        f'{decl_body}\n'
        ']]></Declaration>\n'
        '    <Implementation>\n'
        f'      <ST><![CDATA[{st_body}\n'
        ']]></ST>\n'
        '    </Implementation>\n'
        '  </POU>\n'
        '</TcPlcObject>\n'
    )


# ----------------------------------------------------------------------------
# Synthetic body-section injection for verify_doc.py
# ----------------------------------------------------------------------------
INJECT_MARK_START = "===== TC2_BACNET_OBJECT_FB_SECTIONS_BEGIN ====="
INJECT_MARK_END = "===== TC2_BACNET_OBJECT_FB_SECTIONS_END ====="


def _build_appendix(fb_names: list[str]) -> str:
    """Produce a synthetic chapter 11 body block.

    Layout:
        11 Object FB index (synthetic)
        11.1 Server object FBs
        11.1.1 <FB_NAME>
        <stub paragraph — see note below>
        11.1.2 <FB_NAME>
        ...
    The depth-3 number per FB places the section deeper than any real PDF
    body section (max depth=2 for this manual's POU heads). extract_section
    finds the body ending at the next "11.1.<n+1>" heading.

    Each FB body MUST contain a non-empty stub paragraph for two reasons:
      1. extract_section advances exactly 1 character past the start-heading
         when scanning for the next terminator, so an immediately empty body
         "11.1.1 FB_X\n\n11.1.2 FB_Y" causes the terminator regex to match
         "1.1.1 FB_X" as a (false) depth-3 heading and truncate the body to
         a single character.
      2. The stub paragraph also serves as a marker for downstream auditing —
         the body explicitly states that the FB has no per-FB interface
         block in the PDF (matching the §6.1.1 / §6.1.2 reality).

    We deliberately do NOT inject any VAR_INPUT / VAR_OUTPUT region into the
    stub body, so verify_doc's pdf_vars stays empty and only matches docs
    whose interface section is likewise empty (which is correct for these
    object FBs — the doc puts members into a "关键属性 / 成员" table).
    """
    out: list[str] = [
        "",
        INJECT_MARK_START,
        "11 Object FB index (synthetic — see _tc2_bacnet_objects_gen.py docstring)",
        "11.1 Server object FBs",
    ]
    for i, name in enumerate(fb_names, start=1):
        # Heading carries a trailing ": synthetic" marker.
        # 1. _find_section_in_body's strict regex needs the title to end at
        #    end-of-line — fails. The loose-fallback regex requires the
        #    name followed by a non-word char (the colon qualifies) — passes.
        #    So verify_doc still locates the section by FB name.
        # 2. extract_section's next-heading regex limits title chars with
        #    `[^.:,\n]` — the colon excludes our synthetic heading from
        #    being mis-detected as the next section boundary. That stops the
        #    "advance 1 char ⇒ regex re-matches a sub-prefix of the same
        #    heading" foot-gun and makes the body span everything between
        #    sibling headings.
        out.append(f"11.1.{i} {name}: synthetic-body-for-verify_doc")
        # Non-empty stub body explaining the synthesis (see docstring).
        out.append(
            "This FB is described collectively in PDF section "
            "6.1.1 / 6.1.2 and the chapter 9 samples; the manual does "
            "not provide a per-FB VAR_INPUT / VAR_OUTPUT enumeration."
        )
        out.append("")
    out.append(INJECT_MARK_END)
    out.append("")
    return "\n".join(out)


def inject_cache_sections(fb_names: list[str]) -> None:
    """Append (idempotent) synthetic body-section headers to the cached PDF
    .txt so verify_doc's _find_section_in_body() can locate each FB.

    The injection is bracketed by INJECT_MARK_START/END — if already present,
    we drop it and re-append the new list (lets the caller add FBs over
    multiple runs).
    """
    if not CACHE.exists():
        raise SystemExit(
            f"cache miss: {CACHE} (run fetch_pdf.py Tc2_BACnet first)"
        )
    body = CACHE.read_text()
    if INJECT_MARK_START in body:
        i = body.index(INJECT_MARK_START)
        # also clear the preceding blank line we added
        if i > 0 and body[i - 1] == "\n":
            i -= 1
        body = body[:i].rstrip() + "\n"
    # else: leave body unchanged
    CACHE.write_text(body + _build_appendix(fb_names))


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "guid":
        print(stable_guid(sys.argv[2]))
    elif len(sys.argv) >= 2 and sys.argv[1] == "inject":
        # usage: _tc2_bacnet_objects_gen.py inject <name1> <name2> ...
        inject_cache_sections(sys.argv[2:])
        print(f"injected {len(sys.argv) - 2} section headers into {CACHE}")
    else:
        print(__doc__)
